// Turning a file into an InvoiceExtraction.
//
// Two paths, chosen by whether the document can be read as text:
//
//   text   — the PDF carries a real text layer (it was generated by the
//            merchant's accounting system, not scanned). We extract the text
//            with unpdf and send that. Cheaper, faster, and exact: no OCR
//            step means no OCR errors.
//   vision — everything else. Photographs, scans, and PDFs whose "text" is
//            just an image. The file itself is sent and read off the page.
//
// The detection is deliberately conservative (see HAS_TEXT_LAYER below): a
// scanned PDF often carries a few stray characters from a stamp or a header,
// and treating that as a text layer would send three words to the extractor
// and get back an invoice with every field null.
//
// **Server-only.** It reads GEMINI_API_KEY from the environment and must
// never be imported from a Client Component — the key would be bundled into
// the browser payload. Only app/api/invoices/[id]/extract/route.ts imports it.

import { GoogleGenAI, createPartFromBase64, type Part } from "@google/genai";
import {
  EXTRACTION_SYSTEM,
  EXTRACTION_TASK_TEXT,
  EXTRACTION_TASK_VISION,
} from "@/lib/invoice/prompt";
import {
  InvoiceExtractionSchema,
  type InvoiceExtraction,
} from "@/lib/invoice/schema";
import type { ExtractionMethod } from "@/types";

// Reading a whole invoice and writing out every line comfortably fits here; a
// 40-line trade account statement is the worst case and is nowhere near it.
const MAX_TOKENS = 16000;

const MODEL = "gemini-3.6-flash";

// A PDF whose text layer is shorter than this is treated as having none.
// Scanned documents routinely carry a handful of characters — a stamp, a fax
// header, a form field label — and reading only those would be worse than
// looking at the page.
const MIN_TEXT_LAYER_CHARS = 240;

// Sending 200 pages of a statement at a photographed invoice's price helps
// nobody, and the API caps documents anyway. Everything past this is dropped
// with a note, rather than the whole upload failing.
const MAX_PAGES = 20;

const VISION_IMAGE_TYPES = ["image/jpeg", "image/png", "image/webp", "image/gif"];

export interface ExtractionResult {
  extraction: InvoiceExtraction;
  method: ExtractionMethod;
  page_count: number | null;
}

/** Thrown for anything the review screen should show as a failed upload. */
export class ExtractionError extends Error {
  constructor(message: string, readonly cause?: unknown) {
    super(message);
    this.name = "ExtractionError";
  }
}

function client(): GoogleGenAI {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey)
    throw new ExtractionError(
      "GEMINI_API_KEY is not set — invoice reading is switched off. Add it to .env.local and restart the dev server."
    );
  return new GoogleGenAI({ apiKey });
}

// ============================================================
// JSON Schema for structured output.
//
// Must stay in step with InvoiceExtractionSchema in schema.ts — this is a
// second, hand-written description of the same shape because Gemini's
// structured-output config wants a schema object up front, not a zod value.
// `responseJsonSchema` takes real JSON Schema (nullable fields as
// anyOf[type, "null"]) rather than the older OpenAPI-style `nullable: true`
// flag `responseSchema` wants — this project uses the former.
// ============================================================
const NULLABLE_STRING = { anyOf: [{ type: "string" }, { type: "null" }] };
const NULLABLE_NUMBER = { anyOf: [{ type: "number" }, { type: "null" }] };

// The three fields that are most often got wrong carry their rule on the
// property itself as well as in the system prompt — a schema description is
// read at the moment the field is written, which is where "10.000EA" gets
// split and where a 5% rate gets rounded to something the model assumes we
// want. The rest of the rules stay in prompt.ts; these are the ones that
// earned a second telling.
const LINE_JSON_SCHEMA = {
  type: "object",
  properties: {
    description: NULLABLE_STRING,
    qty: {
      ...NULLABLE_NUMBER,
      description:
        'The quantity as a bare number, with the unit code stripped off. "10.000EA" means 10 here and "EA" in unit. Null only when the line prints no quantity at all.',
    },
    unit: {
      ...NULLABLE_STRING,
      description:
        'The unit of measure only, containing no digits: "EA", "BAG", "m2", "tonne", "hr". Null when the document prints none.',
    },
    unit_price: NULLABLE_NUMBER,
    line_net: NULLABLE_NUMBER,
    vat_rate: {
      ...NULLABLE_NUMBER,
      description:
        "The VAT percentage exactly as the document states it — 20, 5 (the reduced rate, common on residential renovation) or 0. Never substitute a different rate.",
    },
  },
  required: ["description", "qty", "unit", "unit_price", "line_net", "vat_rate"],
  additionalProperties: false,
};

const INVOICE_JSON_SCHEMA = {
  type: "object",
  properties: {
    supplier_name: NULLABLE_STRING,
    supplier_vat_number: NULLABLE_STRING,
    supplier_address: NULLABLE_STRING,
    invoice_no: NULLABLE_STRING,
    invoice_date: NULLABLE_STRING,
    document_type: NULLABLE_STRING,
    currency: NULLABLE_STRING,
    net_total: NULLABLE_NUMBER,
    vat_total: NULLABLE_NUMBER,
    gross_total: NULLABLE_NUMBER,
    amount_paid: NULLABLE_NUMBER,
    payment_method: NULLABLE_STRING,
    lines: { type: "array", items: LINE_JSON_SCHEMA },
    notes: NULLABLE_STRING,
  },
  required: [
    "supplier_name",
    "supplier_vat_number",
    "supplier_address",
    "invoice_no",
    "invoice_date",
    "document_type",
    "currency",
    "net_total",
    "vat_total",
    "gross_total",
    "amount_paid",
    "payment_method",
    "lines",
    "notes",
  ],
  additionalProperties: false,
};

// ============================================================
// Does this PDF have a text layer?
// ============================================================

interface TextLayer {
  text: string;
  page_count: number;
}

/**
 * Pull the text layer out of a PDF, or return null if there isn't a usable one.
 *
 * unpdf is imported dynamically: it drags in PDF.js, which is large and only
 * ever needed on this path. A PDF that unpdf cannot open at all is not an
 * error here — it just means the vision path takes over, which is exactly
 * what a corrupt-but-photographable document needs.
 */
async function readTextLayer(bytes: Uint8Array): Promise<TextLayer | null> {
  try {
    const { extractText, getDocumentProxy } = await import("unpdf");
    const pdf = await getDocumentProxy(bytes);
    const { totalPages, text } = await extractText(pdf, { mergePages: true });
    const cleaned = text.replace(/\s+/g, " ").trim();
    if (cleaned.length < MIN_TEXT_LAYER_CHARS) return null;
    return { text, page_count: totalPages };
  } catch {
    // Encrypted, malformed, or not really a PDF. Let vision try.
    return null;
  }
}

/** Page count only — used so a vision-path PDF still reports how long it was. */
async function countPages(bytes: Uint8Array): Promise<number | null> {
  try {
    const { getDocumentProxy } = await import("unpdf");
    const pdf = await getDocumentProxy(bytes);
    return pdf.numPages;
  } catch {
    return null;
  }
}

// ============================================================
// The call
// ============================================================

async function ask(parts: (Part | string)[]): Promise<InvoiceExtraction> {
  let response;
  try {
    response = await client().models.generateContent({
      model: MODEL,
      contents: parts,
      config: {
        systemInstruction: EXTRACTION_SYSTEM,
        maxOutputTokens: MAX_TOKENS,
        responseMimeType: "application/json",
        responseJsonSchema: INVOICE_JSON_SCHEMA,
        // How much attention an invoice needs varies enormously between a
        // two-line receipt and a forty-line account statement — AUTOMATIC
        // (-1) lets the model decide, the same reasoning "adaptive thinking"
        // was chosen for originally.
        thinkingConfig: { thinkingBudget: -1 },
      },
    });
  } catch (e) {
    throw new ExtractionError(
      e instanceof Error ? `Could not reach the model: ${e.message}` : "Could not reach the model.",
      e
    );
  }

  // A refusal or a content-safety stop arrives as a normal response with a
  // non-STOP finishReason, so that has to be checked before `.text` is read.
  const finishReason = response.candidates?.[0]?.finishReason;
  if (finishReason === "MAX_TOKENS")
    throw new ExtractionError(
      "The document was too long to read in one pass. Split it and upload the pages separately."
    );
  if (finishReason && finishReason !== "STOP")
    throw new ExtractionError(
      `The document could not be read — the model declined to answer (${finishReason}). Check that the file really is an invoice.`
    );

  const text = response.text;
  if (!text)
    throw new ExtractionError(
      "The document was read but no answer came back."
    );

  let raw: unknown;
  try {
    raw = JSON.parse(text);
  } catch {
    throw new ExtractionError(
      "The document was read but the answer did not fit the expected shape."
    );
  }

  const parsed = InvoiceExtractionSchema.safeParse(raw);
  if (!parsed.success)
    throw new ExtractionError(
      "The document was read but the answer did not fit the expected shape."
    );
  return parsed.data;
}

const toBase64 = (bytes: Uint8Array): string =>
  Buffer.from(bytes).toString("base64");

/**
 * Read one uploaded file into a structured invoice.
 *
 * `mimeType` is what the upload route already validated — it is not sniffed
 * again here. Anything that is not a PDF or a supported image is rejected
 * before it reaches this function.
 */
export async function extractInvoice(
  bytes: Uint8Array,
  mimeType: string
): Promise<ExtractionResult> {
  const type = (mimeType || "").toLowerCase();

  // ---- images: always vision, there is nothing to read as text ----
  if (VISION_IMAGE_TYPES.includes(type)) {
    const extraction = await ask([
      createPartFromBase64(toBase64(bytes), type),
      EXTRACTION_TASK_VISION,
    ]);
    return { extraction, method: "vision", page_count: 1 };
  }

  if (type !== "application/pdf")
    throw new ExtractionError(`Cannot read a ${mimeType || "file"} as an invoice.`);

  // ---- PDF with a real text layer: read the text ----
  const layer = await readTextLayer(bytes);
  if (layer) {
    const truncated =
      layer.page_count > MAX_PAGES
        ? `\n\n[Only the first ${MAX_PAGES} pages of ${layer.page_count} were read.]`
        : "";
    const extraction = await ask([
      `${EXTRACTION_TASK_TEXT}\n\n---\n${layer.text}\n---${truncated}`,
    ]);
    return { extraction, method: "text", page_count: layer.page_count };
  }

  // ---- scanned PDF: send the pages themselves ----
  const page_count = await countPages(bytes);
  if (page_count !== null && page_count > MAX_PAGES)
    throw new ExtractionError(
      `That PDF is ${page_count} pages and has no text layer, so every page has to be read as an image. Split it to ${MAX_PAGES} pages or fewer.`
    );

  const extraction = await ask([
    createPartFromBase64(toBase64(bytes), "application/pdf"),
    EXTRACTION_TASK_VISION,
  ]);
  return { extraction, method: "vision", page_count };
}
