import sys, importlib.util
from pathlib import Path
spec = importlib.util.spec_from_file_location("b", "scripts/build_import_sql.py")
b = importlib.util.module_from_spec(spec); spec.loader.exec_module(b)

diary, _ = b.parse_diary()
paid = [r for r in diary if r["paid"] > 0]
total = round(sum(r["paid"] for r in paid), 2)

vals = ",\n".join(
    f"    ({r['week']}, {b.q(r['description'])}, {r['quoted']}, '{r['paid_date']}'::date)"
    for r in paid
)

sql = f"""-- RenovaTrack — mark the diary rows that the spreadsheet shows as paid.
-- GENERATED by scripts/gen_mark_paid_sql.py — do not hand-edit.
--
-- Why: File 1's 'Week-by-Week Plan' has 'Planned' in the Status column on all
-- 40 rows — the sheet never sets it. What actually records a payment is the
-- 'Paid Date' column, filled on {len(paid)} rows (weeks 1-7). 0005 imported the
-- literal Status, so every row landed as Planned and Paid to Date showed £0.00.
--
-- The dates are hand-typed day/month with a weekday and no year ('Friday 27/2').
-- Every one falls on the stated weekday only in 2026, so the year is resolved
-- from the weekday rather than assumed.
--
-- Idempotent: re-running changes nothing. Also a no-op after re-running an
-- up-to-date 0005, which now applies the same rule at import time.
--
-- Run in the Supabase SQL editor, after 0005.

begin;

do $$
declare
  v_user    uuid := '{b.USER_ID}';
  v_project uuid;
  v_rows    int;
begin
  select id into v_project
  from public.projects
  where user_id = v_user and name = {b.q(b.PROJECT_NAME)};

  if v_project is null then
    raise exception 'Project % not found for user % — run 0005 first.',
      {b.q(b.PROJECT_NAME)}, v_user;
  end if;

  with paid(week_number, description, quoted_amount, paid_date) as (
    values
{vals}
  )
  update public.expense_entries e
  set status      = 'Paid',
      paid_amount = e.actual_amount,
      paid_date   = p.paid_date,
      -- The free-text date note exists only because paid_date could not hold
      -- it. Now that it can, drop the marker and tidy any stranded separator.
      notes = nullif(btrim(
                -- 2. re-normalise the ' | ' separators the cut may have left ragged
                regexp_replace(
                  -- 1. drop the marker and the separator in front of it
                  regexp_replace(coalesce(e.notes, ''),
                                 '\\s*\\|?\\s*Paid date \\(as written\\):[^|]*', '', 'g'),
                  '\\s*\\|\\s*', ' | ', 'g'),
                ' |'), '')
  from paid p
  where e.project_id    = v_project
    and e.source        = 'diary'
    and e.week_number   = p.week_number
    and e.description   = p.description
    and e.quoted_amount = p.quoted_amount;

  get diagnostics v_rows = row_count;
  raise notice 'Marked % diary rows as Paid (expected {len(paid)}).', v_rows;

  if v_rows <> {len(paid)} then
    raise exception 'Expected to update {len(paid)} rows but updated % — aborting.', v_rows;
  end if;
end $$;

-- Verify before committing. Expect: {len(paid)} paid rows, paid_total {total},
-- and 0 rows left carrying the old free-text date note.
select count(*) filter (where status = 'Paid')                     as paid_rows,
       count(*) filter (where status = 'Planned')                  as planned_rows,
       sum(paid_amount)                                            as paid_total,
       count(*) filter (where notes like '%Paid date (as written)%') as stale_notes
from public.expense_entries
where source = 'diary'
  and project_id = (select id from public.projects
                    where user_id = '{b.USER_ID}' and name = {b.q(b.PROJECT_NAME)});

commit;
-- rollback;  -- use instead of commit if the numbers look wrong
"""
Path("supabase/migrations/0006_mark_paid_entries.sql").write_text(sql, encoding="utf-8")
print(f"wrote 0006 — {len(paid)} rows, paid total {total}")
