import { requireUser, json, error } from "@/lib/api";
import { validateLabourEntry, hasErrors, todayISO } from "@/lib/validation";
import { createPurchase } from "@/lib/purchaseWrite";
import { round2, SETTLED_TOLERANCE } from "@/lib/purchases";
import type { PaymentMethod, PurchaseInput } from "@/types";

// Log a day's labour: a name, a rate, hours and a total, optionally with the
// payment already made.
//
// What this is NOT is a second kind of record. It writes one ordinary purchase
// with one Labour line, through the same lib/purchaseWrite.ts path the invoice
// form uses, precisely so that every builder in lib/invoiceViews.ts — Labour,
// Trades, Suppliers, Overview, Price Tracker — picks it up with no changes at
// all. If it needed special-casing anywhere downstream, it would be the wrong
// shape here.
//
// The mapping from what you type to what is stored:
//   name       → purchase_lines.description_raw  (NOT a supplier row: a worker
//                is a person, and inventing a merchant for them would put them
//                on the Suppliers screen as a company)
//   trade      → purchases.trade                  (free text, no FK, as always)
//   rate       → purchase_lines.unit_price, with unit = 'hr'
//   hours      → purchase_lines.qty
//   total pay  → purchase_lines.line_net          (ex-VAT, and authoritative —
//                the server does not recompute it from rate × hours)
//   vat rate   → purchase_lines.vat_rate
//   status     → purchases.entry_status
//
// Fixed, never asked: category = 'Labour', invoice_no = null, supplier_id =
// null, and (inside createPurchase) origin = 'manual', entry_source = 'diary'.
// net_total and vat_total are summed from the line by purchaseTotalsFromLines;
// gross_total is generated by Postgres and is never written.

const text = (value: unknown): string | null => {
  const trimmed = String(value ?? "").trim();
  return trimmed === "" ? null : trimmed;
};

export async function POST(req: Request, { params }: { params: { id: string } }) {
  const auth = await requireUser();
  if ("response" in auth) return auth.response;

  const body = await req.json().catch(() => ({}));
  const errors = validateLabourEntry(body);
  if (hasErrors(errors)) return error("Validation failed", 422, errors);

  // RLS enforces ownership too; this turns "not yours" into a 404 rather than
  // a foreign-key failure. Same check the invoice route makes.
  const { data: project } = await auth.supabase
    .from("projects")
    .select("id")
    .eq("id", params.id)
    .single();
  if (!project) return error("Project not found", 404);

  const isPaid = body.status === "Paid";
  const paidOn = text(body.paid_on);
  const lineNet = round2(Number(body.total_pay) || 0);
  const vatRate = Number(body.vat_rate);

  // Money already handed over, as a DIFFERENCE rather than as a figure —
  // exactly the rule PATCH /api/projects/[id]/expenses/[eid] applies to Mark
  // Paid. An invoice has no paid column: what has been paid is the sum of its
  // payments rows, so anything that sets it has to write the gap between the
  // two. A brand-new purchase has no payments yet, so the gap is the whole
  // amount — but it is computed rather than assumed, so this stays correct if
  // a labour entry ever gains an edit path of its own.
  const alreadyPaid = 0;
  const delta = isPaid ? round2(Number(body.paid_amount ?? 0) - alreadyPaid) : 0;

  const input: PurchaseInput = {
    // Empty, so resolveSupplierId returns null and no supplier row is created.
    supplier_name: "",
    // The day the work was paid for when we know it, otherwise today. The
    // column is nullable, but a labour entry with no date at all sorts to the
    // top of every list and shows "—" on the Labour tab, which is worse than a
    // date that is right to the day it was logged.
    purchase_date: isPaid ? paidOn : todayISO(),
    week_no: null,
    invoice_no: null,
    category: "Labour",
    trade: text(body.trade),
    location_room: null,
    notes: text(body.notes),
    entry_status: body.status,
    lines: [
      {
        item_id: null,
        description_raw: String(body.name ?? "").trim(),
        qty: Number(body.hours) || 0,
        unit: "hr",
        unit_price: Number(body.rate) || 0,
        // What was typed, not rate × hours. The form warns when the two
        // disagree and offers to fix it; it never silently overwrites.
        line_net: lineNet,
        vat_rate: vatRate,
      },
    ],
    // Planned / In Progress / Cancelled write no payment row at all — a
    // zero-amount placeholder would show up as a payment record that says
    // nothing happened, and paymentRows() drops it anyway.
    payments:
      delta > SETTLED_TOLERANCE
        ? [
            {
              paid_on: paidOn,
              amount: delta,
              method: body.payment_method as PaymentMethod,
              reference: null,
            },
          ]
        : [],
  };

  try {
    const purchase = await createPurchase(
      auth.supabase,
      auth.user.id,
      params.id,
      input
    );
    return json(purchase, 201);
  } catch (e) {
    return error(
      e instanceof Error ? e.message : "Could not save the labour entry",
      500
    );
  }
}
