-- RenovaTrack — rebuild data after the cascade delete.
-- GENERATED by scripts/build_import_sql.py — do not hand-edit.
--
-- Owner : 5d3fc9ff-92a3-4923-a18b-7eb5eade3105 (admin@pk.com)
-- Diary : 40 rows, weeks 1-15
-- Ledger: 96 rows
-- Trades: 16 lookups
--
-- Run in the Supabase SQL editor. Re-runnable: it deletes this
-- user's existing rows for the project first.

begin;

do $$
declare
  v_user    uuid := '5d3fc9ff-92a3-4923-a18b-7eb5eade3105';
  v_project uuid;
begin
  if not exists (select 1 from auth.users where id = v_user) then
    raise exception 'User % not found in auth.users.', v_user;
  end if;

  -- Idempotency: clear any prior import of this project.
  delete from public.projects where user_id = v_user and name = '46 Glenferrie Road';

  insert into public.projects (user_id, name, target_budget, status, notes)
  values (v_user, '46 Glenferrie Road', 98932.12, 'active',
          'Rebuilt from spreadsheets after auth user deletion.')
  returning id into v_project;

  insert into public.expense_entries (user_id, project_id, week_number, description, category, trade, location_room, notes, supplier, invoice_ref, paid_date, payment_method, qty, unit_cost, vat_rate, status, quoted_amount, actual_amount, paid_amount, source) values
  (v_user, v_project, 1, 'Labourers', 'Labour', 'General Builder', null, 'Clearence - 6 man days | Paid date (as written): Friday 27/2 | Rate: 45.0', null, null, null, 'Cash', 0, 0, 0, 'Planned', 450.0, 450.0, 0, 'diary'),
  (v_user, v_project, 1, 'DMC - Dave', 'Labour', 'General Builder', null, 'Dave first day on site | Paid date (as written): Friday 27/2 | Rate: 45.0', null, null, null, 'Cash', 0, 0, 0, 'Planned', 220.0, 220.0, 0, 'diary'),
  (v_user, v_project, 1, 'Adam - Clearance', 'Labour', 'Skip/Disposal', null, 'Rubbish Removal | Paid date (as written): Friday 27/2', null, null, null, 'Cash', 0, 0, 0, 'Planned', 1100.0, 1100.0, 0, 'diary'),
  (v_user, v_project, 2, 'Labourers', 'Labour', 'General Builder', null, 'Clearence / back to brick - 9 d | Paid date (as written): Friday 6/3 | Rate: 45.0', null, null, null, 'Cash', 0, 0, 0, 'Planned', 675.0, 675.0, 0, 'diary'),
  (v_user, v_project, 2, 'Adam - Clearance', 'Labour', 'Skip/Disposal', null, 'Rubbish Removal | Paid date (as written): Friday 6/3', null, null, null, 'Cash', 0, 0, 0, 'Planned', 1000.0, 1000.0, 0, 'diary'),
  (v_user, v_project, 3, 'Labourers', 'Labour', 'General Builder', null, 'Clearence / back to brick - 7 d | Paid date (as written): Friday 13/3 | Rate: 45.0', null, null, null, 'Cash', 0, 0, 0, 'Planned', 525.0, 525.0, 0, 'diary'),
  (v_user, v_project, 4, 'Labourers', 'Labour', 'General Builder', null, 'Clearance 6d | Paid date (as written): Friday 20/3 | Rate: 45.0', null, null, null, 'Cash', 0, 0, 0, 'Planned', 450.0, 450.0, 0, 'diary'),
  (v_user, v_project, 4, 'Adam - Clearance', 'Labour', 'Skip/Disposal', null, 'Paid date (as written): Friday 20/3', null, null, null, 'Cash', 0, 0, 0, 'Planned', 1100.0, 1100.0, 0, 'diary'),
  (v_user, v_project, 5, 'Skip', 'Labour', 'Skip/Disposal', null, 'Paid date (as written): Friday 27/3', 'Stevenage Skips', null, null, 'Cash', 0, 0, 0, 'Planned', 480.0, 480.0, 0, 'diary'),
  (v_user, v_project, 5, 'Labourers', 'Labour', 'General Builder', null, 'Paid date (as written): Friday 27/3 | Rate: 45.0', null, null, null, 'Cash', 0, 0, 0, 'Planned', 450.0, 450.0, 0, 'diary'),
  (v_user, v_project, 5, 'Dave Barker (Groundwork)', 'Labour', 'General Builder', null, 'Paid date (as written): Friday 27/3 | Rate: 45.0', null, null, null, 'Cash', 0, 0, 0, 'Planned', 1250.0, 1250.0, 0, 'diary'),
  (v_user, v_project, 5, 'Master Mix', 'Materials', 'Other', null, 'Paid date (as written): Friday 27/3 | Rate: 50.0', null, null, null, 'Debit Card', 0, 0, 0, 'Planned', 1025.0, 1025.0, 0, 'diary'),
  (v_user, v_project, 6, 'Labourers', 'Labour', 'General Builder', null, 'Paid date (as written): Friday 3/4 | Rate: 45.0', null, null, null, 'Cash', 0, 0, 0, 'Planned', 300.0, 300.0, 0, 'diary'),
  (v_user, v_project, 6, 'Dave Barker (Groundwork)', 'Labour', 'General Builder', null, 'Paid date (as written): Friday 3/4 | Rate: 45.0', null, null, null, 'Cash', 0, 0, 0, 'Planned', 900.0, 900.0, 0, 'diary'),
  (v_user, v_project, 6, 'Dave Builder', 'Labour', 'General Builder', null, 'Paid date (as written): Friday 3/4 | Rate: 45.0', null, null, null, 'Cash', 0, 0, 0, 'Planned', 300.0, 300.0, 0, 'diary'),
  (v_user, v_project, 6, 'Steels', 'Materials', 'General Builder', null, 'Paid date (as written): Friday 3/4 | Rate: 45.0', null, null, null, 'Cash', 0, 0, 0, 'Planned', 1000.0, 1000.0, 0, 'diary'),
  (v_user, v_project, 7, 'SDE Drainage', 'Materials', 'General Builder', null, 'Paid date (as written): Friday 10/4 | Rate: 45.0', null, null, null, 'Credit Card', 0, 0, 20, 'Planned', 98.4, 98.4, 0, 'diary'),
  (v_user, v_project, 7, 'Master Mix', 'Materials', 'General Builder', null, 'Paid date (as written): Friday 10/4 | Rate: 45.0', null, null, null, 'Debit Card', 0, 0, 20, 'Planned', 900.0, 900.0, 0, 'diary'),
  (v_user, v_project, 7, 'Labourers', 'Labour', 'General Builder', null, 'Paid date (as written): FRIDAY 10/4 | Rate: 45.0', null, null, null, 'Cash', 0, 0, 0, 'Planned', 450.0, 450.0, 0, 'diary'),
  (v_user, v_project, 7, 'Dave', 'Labour', 'General Builder', null, 'Paid date (as written): Friday 10/4 | Rate: 45.0', '£300 PAID FROM OWED', null, null, 'Cash', 0, 0, 0, 'Planned', 600.0, 600.0, 0, 'diary'),
  (v_user, v_project, 8, 'dave', 'Labour', 'General Builder', null, 'Rate: 45.0', '£400 paid from whats owed', null, null, null, 0, 0, 0, 'Planned', 1400.0, 1400.0, 0, 'diary'),
  (v_user, v_project, 8, 'Labourers', 'Labour', 'General Builder', null, 'Rate: 45.0', null, null, null, null, 0, 0, 0, 'Planned', 750.0, 750.0, 0, 'diary'),
  (v_user, v_project, 8, 'Owen Brickwork', 'Labour', 'General Builder', null, 'Rate: 45.0', '1 day - to DPC', null, null, null, 0, 0, 0, 'Planned', 275.0, 275.0, 0, 'diary'),
  (v_user, v_project, 9, 'Owen Brickwork', 'Labour', 'General Builder', null, 'Rate: 45.0', 'all brickwork completed', null, null, null, 0, 0, 0, 'Planned', 1935.0, 1935.0, 0, 'diary'),
  (v_user, v_project, 9, 'Dave Builder', 'Labour', 'General Builder', null, 'Rate: 45.0', 'steels in', null, null, null, 0, 0, 0, 'Planned', 2035.0, 2035.0, 0, 'diary'),
  (v_user, v_project, 9, 'Labourers', 'Labour', 'General Builder', null, 'Rate: 45.0', 'steels help plus disposal', null, null, null, 0, 0, 0, 'Planned', 900.0, 900.0, 0, 'diary'),
  (v_user, v_project, 9, 'Toby', 'Labour', 'Skip/Disposal', null, null, 'Toby cleared out huge earth pile', null, null, null, 0, 0, 0, 'Planned', 1240.0, 1240.0, 0, 'diary'),
  (v_user, v_project, 10, 'Dave Builder', 'Labour', 'General Builder', null, 'Rate: 45.0', null, null, null, null, 0, 0, 0, 'Planned', 1640.0, 1640.0, 0, 'diary'),
  (v_user, v_project, 10, 'Owen Brickwork', 'Labour', 'General Builder', null, 'Rate: 45.0', null, null, null, null, 0, 0, 0, 'Planned', 675.0, 675.0, 0, 'diary'),
  (v_user, v_project, 10, 'Labourers', 'Labour', 'General Builder', null, 'Rate: 45.0', null, null, null, null, 0, 0, 0, 'Planned', 600.0, 600.0, 0, 'diary'),
  (v_user, v_project, 11, 'Dave Builder', 'Labour', 'General Builder', null, 'Rate: 45.0', null, null, null, null, 0, 0, 0, 'Planned', 400.0, 400.0, 0, 'diary'),
  (v_user, v_project, 11, 'Labourers', 'Labour', 'General Builder', null, 'Rate: 45.0', null, null, null, null, 0, 0, 0, 'Planned', 300.0, 300.0, 0, 'diary'),
  (v_user, v_project, 12, 'Scaffold', 'Materials', 'Scaffolder', null, 'Rate: 55.0', null, null, null, null, 0, 0, 0, 'Planned', 1000.0, 1000.0, 0, 'diary'),
  (v_user, v_project, 12, 'Nick Loft', 'Labour', 'General Builder', null, 'Rate: 45.0', null, null, null, null, 0, 0, 0, 'Planned', 3000.0, 3000.0, 0, 'diary'),
  (v_user, v_project, 13, 'Labourers', 'Labour', 'General Builder', null, 'Rate: 45.0', null, null, null, null, 0, 0, 0, 'Planned', 300.0, 300.0, 0, 'diary'),
  (v_user, v_project, 13, 'Adam - Clearance', 'Labour', 'Skip/Disposal', null, null, null, null, null, null, 0, 0, 0, 'Planned', 275.0, 275.0, 0, 'diary'),
  (v_user, v_project, 13, 'Nick Loft', 'Labour', 'General Builder', null, 'Rate: 45.0', null, null, null, null, 0, 0, 0, 'Planned', 2000.0, 2000.0, 0, 'diary'),
  (v_user, v_project, 14, 'Nick Loft', null, null, null, null, null, null, null, null, 0, 0, 0, 'Planned', 2520.0, 2520.0, 0, 'diary'),
  (v_user, v_project, 15, 'Nick Loft', 'Labour', 'General Builder', null, 'Rate: 45.0', null, null, null, null, 0, 0, 0, 'Planned', 2520.0, 2520.0, 0, 'diary'),
  (v_user, v_project, 15, 'Lawsons', 'Materials', 'Other', null, 'Rate: 50.0', null, null, null, null, 0, 0, 20, 'Planned', 5373.41, 5373.41, 0, 'diary'),
  (v_user, v_project, 1, 'Vince', 'Labour', null, null, '2 days', 'Vince', null, '2025-11-17'::date, null, 0, 0, 0, 'Paid', 440.0, 440.0, 440.0, 'ledger'),
  (v_user, v_project, 1, 'Venkat', 'Labour', null, null, '6 days', 'Venkat', null, '2025-11-17'::date, null, 0, 0, 0, 'Paid', 525.0, 525.0, 525.0, 'ledger'),
  (v_user, v_project, 1, 'Dave Gardener', 'Labour', null, null, null, 'Dave Gardener', null, '2025-11-17'::date, null, 0, 0, 0, 'Paid', 1350.0, 1350.0, 1350.0, 'ledger'),
  (v_user, v_project, 1, 'James Chippy', 'Labour', null, null, '2 days plus fixings', 'James Chippy', null, '2025-11-13'::date, null, 0, 0, 0, 'Paid', 510.0, 510.0, 510.0, 'ledger'),
  (v_user, v_project, 1, 'Vince', 'Labour', null, null, '5 days - £540 towards Mac', 'Vince', null, '2025-11-14'::date, null, 0, 0, 0, 'Paid', 1100.0, 1100.0, 1100.0, 'ledger'),
  (v_user, v_project, 1, 'Venkat', 'Labour', null, null, '5 days', 'Venkat', null, '2025-11-14'::date, null, 0, 0, 0, 'Paid', 375.0, 375.0, 375.0, 'ledger'),
  (v_user, v_project, 1, 'James Chippy', 'Labour', null, null, '1 day plus materials', 'James Chippy', null, '2025-11-20'::date, null, 0, 0, 0, 'Paid', 270.0, 270.0, 270.0, 'ledger'),
  (v_user, v_project, 1, 'Dave Gardener', 'Labour', null, null, '5 days labour', 'Dave Gardener', null, '2025-11-21'::date, null, 0, 0, 0, 'Paid', 2250.0, 2250.0, 2250.0, 'ledger'),
  (v_user, v_project, 1, 'Venky', 'Labour', null, null, '4 days Venky, 1 day AJ, Anil, Barat', 'Venky', null, '2025-11-21'::date, null, 0, 0, 0, 'Paid', 540.0, 540.0, 540.0, 'ledger'),
  (v_user, v_project, 1, 'Vince + Simon', 'Labour', null, null, '2 days for UFH + Chippy studs in bathrooms (£480 to mac)', 'Vince + Simon', null, '2025-11-21'::date, null, 0, 0, 0, 'Paid', 440.0, 440.0, 440.0, 'ledger'),
  (v_user, v_project, 1, 'Dave Gardener', 'Labour', null, null, '3 days to finish back garden inc slabbing all around 100m2', 'Dave Gardener', null, '2025-11-28'::date, null, 0, 0, 0, 'Paid', 1350.0, 1350.0, 1350.0, 'ledger'),
  (v_user, v_project, 1, 'Dave / Simon', 'Labour', null, null, '5 days - gutters / fascias entire week (! Day on fixing window area)', 'Dave / Simon', null, '2025-11-28'::date, null, 0, 0, 0, 'Paid', 1100.0, 1100.0, 1100.0, 'ledger'),
  (v_user, v_project, 1, 'Martin Plasterer', 'Labour', null, null, '2 days for 3 lads', 'Martin Plasterer', null, '2025-11-28'::date, null, 0, 0, 0, 'Paid', 1000.0, 1000.0, 1000.0, 'ledger'),
  (v_user, v_project, 1, 'Venky', 'Labour', null, null, '7 man days for labourers….. Turfing... Garden …. Then Thurs Frid helping simon with Fascias', 'Venky', null, '2025-11-28'::date, null, 0, 0, 0, 'Paid', 525.0, 525.0, 525.0, 'ledger'),
  (v_user, v_project, 1, 'Plasterers', 'Labour', null, null, '2 plasterers SAT 29/11', 'Plasterers', null, '2025-11-29'::date, null, 0, 0, 0, 'Paid', 400.0, 400.0, 400.0, 'ledger'),
  (v_user, v_project, 1, 'Venky', 'Labour', null, null, '2 days labour', 'Venky', null, '2025-12-05'::date, null, 0, 0, 0, 'Paid', 150.0, 150.0, 150.0, 'ledger'),
  (v_user, v_project, 1, 'Garden', 'Labour', null, null, 'clear 7 tree stumps out front', 'Garden', null, '2025-12-05'::date, null, 0, 0, 0, 'Paid', 300.0, 300.0, 300.0, 'ledger'),
  (v_user, v_project, 1, 'Roof clean plus repair', 'Labour', null, null, null, 'Roof clean plus repair', null, '2025-12-05'::date, null, 0, 0, 0, 'Paid', 1300.0, 1300.0, 1300.0, 'ledger'),
  (v_user, v_project, 1, 'dave', 'Labour', null, null, '2 days simon plus materials', 'dave', null, '2025-12-05'::date, null, 0, 0, 0, 'Paid', 460.0, 460.0, 460.0, 'ledger'),
  (v_user, v_project, 1, 'Tiler', 'Labour', null, null, 'Tiler paid - £2500 remaining', 'Tiler', null, '2025-12-05'::date, null, 0, 0, 0, 'Paid', 1500.0, 1500.0, 1500.0, 'ledger'),
  (v_user, v_project, 1, 'SRI Kitchen fitters', 'Labour', null, null, 'Cash paid', 'SRI Kitchen fitters', null, '2025-12-12'::date, null, 0, 0, 0, 'Paid', 1600.0, 1600.0, 1600.0, 'ledger'),
  (v_user, v_project, 1, 'Tiler', 'Labour', null, null, null, 'Tiler', null, '2025-12-12'::date, null, 0, 0, 0, 'Paid', 1000.0, 1000.0, 1000.0, 'ledger'),
  (v_user, v_project, 1, 'Stuart Miscoat', 'Labour', null, null, 'Spray miscoat', 'Stuart Miscoat', null, '2025-12-12'::date, null, 0, 0, 0, 'Paid', 150.0, 150.0, 150.0, 'ledger'),
  (v_user, v_project, 1, 'Dave / Simon', 'Labour', null, null, 'Paid… £1050….  £50 towards Mac', 'Dave / Simon', null, '2025-12-12'::date, null, 0, 0, 0, 'Paid', 1100.0, 1100.0, 1100.0, 'ledger'),
  (v_user, v_project, 1, 'Dave Gardener', 'Labour', null, null, '1/2 day …. Dave and co slabbed the front…. 15m2 layed', 'Dave Gardener', null, '2025-12-12'::date, null, 0, 0, 0, 'Paid', 225.0, 225.0, 225.0, 'ledger'),
  (v_user, v_project, 1, 'Mickey - Grout Garden', 'Labour', null, null, null, 'Mickey - Grout Garden', null, '2025-12-13'::date, null, 0, 0, 0, 'Paid', 150.0, 150.0, 150.0, 'ledger'),
  (v_user, v_project, 1, 'Tom Chippie', 'Labour', null, null, 'Paid… £30 per hour Tom + £25 / hour for his mate', 'Tom Chippie', null, '2025-11-14'::date, null, 0, 0, 0, 'Paid', 565.0, 565.0, 565.0, 'ledger'),
  (v_user, v_project, 1, 'Venky', 'Labour', null, null, '2.5 days.', 'Venky', null, '2025-12-15'::date, null, 0, 0, 0, 'Paid', 150.0, 150.0, 150.0, 'ledger'),
  (v_user, v_project, 1, 'Dave Gardener', 'Labour', null, null, '1 day dave… finished job', 'Dave Gardener', null, '2025-12-15'::date, null, 0, 0, 0, 'Paid', 300.0, 300.0, 300.0, 'ledger'),
  (v_user, v_project, 1, 'Dan Painter', 'Labour', null, null, '3 days Stu @ £160 + 1 day Dan @ £170', 'Dan Painter', null, '2025-12-19'::date, null, 0, 0, 0, 'Paid', 650.0, 650.0, 650.0, 'ledger'),
  (v_user, v_project, 1, 'Tiler', 'Labour', null, null, 'remaining tile labour - £200 for extra adhesive', 'Tiler', null, '2025-12-19'::date, null, 0, 0, 0, 'Paid', 1610.0, 1610.0, 1610.0, 'ledger'),
  (v_user, v_project, 1, 'Dan Painter', 'Labour', null, null, 'bank transfer', 'Dan Painter', null, '2025-12-23'::date, null, 0, 0, 0, 'Paid', 550.0, 550.0, 550.0, 'ledger'),
  (v_user, v_project, 1, 'Dave Chippie', 'Labour', null, null, 'Chippie for bespoke cupboard in utility', 'Dave Chippie', null, '2026-01-09'::date, null, 0, 0, 0, 'Paid', 220.0, 220.0, 220.0, 'ledger'),
  (v_user, v_project, 1, 'Dan Painter', 'Labour', null, null, null, 'Dan Painter', null, '2026-01-09'::date, null, 0, 0, 0, 'Paid', 1075.0, 1075.0, 1075.0, 'ledger'),
  (v_user, v_project, 1, 'Dan Painter', 'Labour', null, null, null, 'Dan Painter', null, '2026-01-16'::date, null, 0, 0, 0, 'Paid', 100.0, 100.0, 100.0, 'ledger'),
  (v_user, v_project, 1, 'Venkat', 'Labour', null, null, 'final clean up, soffit paints etc', 'Venkat', null, '2026-01-16'::date, null, 0, 0, 0, 'Paid', 100.0, 100.0, 100.0, 'ledger'),
  (v_user, v_project, 1, 'Alspec Windows', 'Materials', null, null, 'Bank T Walkern', 'Alspec Windows', null, '2025-11-02'::date, 'Bank Transfer', 1.0, 5000.0, 0, 'Paid', 5000.0, 5000.0, 5000.0, 'ledger'),
  (v_user, v_project, 1, 'Stevenage Skips', 'Materials', null, null, 'Cash payment', 'Stevenage Skips', null, '2025-11-04'::date, 'Cash', 1.0, 390.0, 0, 'Paid', 390.0, 390.0, 390.0, 'ledger'),
  (v_user, v_project, 1, 'Wunda UFH', 'Materials', null, null, 'Bank T Walkern - Deposit paid 90% remaining', 'Wunda UFH', null, '2025-11-03'::date, 'Bank Transfer', 1.0, 416.05, 0, 'Paid', 416.05, 416.05, 416.05, 'ledger'),
  (v_user, v_project, 1, 'Wunda UFH', 'Materials', null, null, 'Wunda UFH - Bank T', 'Wunda UFH', null, '2025-11-05'::date, 'Bank Transfer', 1.0, 3586.0, 0, 'Paid', 3586.0, 3586.0, 3586.0, 'ledger'),
  (v_user, v_project, 1, 'Kitchen- Cabinets Direct', 'Materials', null, null, 'Paid Cash - £2500 remaining', 'Kitchen- Cabinets Direct', null, '2025-11-07'::date, 'Cash', 1.0, 6000.0, 0, 'Paid', 6000.0, 6000.0, 6000.0, 'ledger'),
  (v_user, v_project, 1, 'Lawsons', 'Materials', null, null, 'Paid Mama', 'Lawsons', null, '2025-11-10'::date, null, 1.0, 336.78, 0, 'Paid', 336.78, 336.78, 336.78, 'ledger'),
  (v_user, v_project, 1, 'Lawsons', 'Materials', null, null, 'Paid Mama', 'Lawsons', null, '2025-11-10'::date, null, 1.0, 252.0, 0, 'Paid', 252.0, 252.0, 252.0, 'ledger'),
  (v_user, v_project, 1, 'Tree Clearence - Garden', 'Materials', null, null, 'Paid Cash', 'Tree Clearence - Garden', null, '2025-11-12'::date, 'Cash', 1.0, 320.0, 0, 'Paid', 320.0, 320.0, 320.0, 'ledger'),
  (v_user, v_project, 1, 'Electrics', 'Materials', null, null, 'Paid Cash', 'Electrics', null, '2025-11-14'::date, 'Cash', 1.0, 4000.0, 0, 'Paid', 4000.0, 4000.0, 4000.0, 'ledger'),
  (v_user, v_project, 1, 'Plumbing', 'Materials', null, null, 'Paid Cash', 'Plumbing', null, '2025-11-15'::date, 'Cash', 1.0, 1000.0, 0, 'Paid', 1000.0, 1000.0, 1000.0, 'ledger'),
  (v_user, v_project, 1, 'Lawsons - Garden £500', 'Materials', null, null, 'Paid Mama', 'Lawsons - Garden £500', null, '2025-11-14'::date, null, 1.0, 655.72, 0, 'Paid', 655.72, 655.72, 655.72, 'ledger'),
  (v_user, v_project, 1, 'Distribution Tiles - GARDEN', 'Materials', null, null, 'Paid Mama', 'Distribution Tiles - GARDEN', null, '2025-11-14'::date, null, 1.0, 1829.16, 0, 'Paid', 1829.16, 1829.16, 1829.16, 'ledger'),
  (v_user, v_project, 1, 'Alpec Windows', 'Materials', null, null, 'Paid Cash', 'Alpec Windows', null, '2025-11-14'::date, 'Cash', 1.0, 1000.0, 0, 'Paid', 1000.0, 1000.0, 1000.0, 'ledger'),
  (v_user, v_project, 1, 'Plumbing', 'Materials', null, null, 'Paid cash', 'Plumbing', null, '2025-11-22'::date, 'Cash', 1.0, 1000.0, 0, 'Paid', 1000.0, 1000.0, 1000.0, 'ledger'),
  (v_user, v_project, 1, 'Pro Tiler', 'Materials', null, null, 'Paid AMEX - Prima + ditra + Adhesive', 'Pro Tiler', null, '2025-11-20'::date, null, 1.0, 1164.14, 0, 'Paid', 1164.14, 1164.14, 1164.14, 'ledger'),
  (v_user, v_project, 1, 'Sam- Hedge removal + clear - Garden', 'Materials', null, null, 'paid cash', 'Sam- Hedge removal + clear - Garden', null, '2025-11-19'::date, 'Cash', 1.0, 200.0, 0, 'Paid', 200.0, 200.0, 200.0, 'ledger'),
  (v_user, v_project, 1, 'Lusso Stone', 'Materials', null, null, 'Paid dad debit card', 'Lusso Stone', null, '2025-11-20'::date, 'Debit Card', 1.0, 1456.0, 0, 'Paid', 1456.0, 1456.0, 1456.0, 'ledger'),
  (v_user, v_project, 1, 'Eurocell', 'Materials', null, null, 'Paid cash', 'Eurocell', null, '2025-11-21'::date, 'Cash', 1.0, 650.0, 0, 'Paid', 650.0, 650.0, 650.0, 'ledger'),
  (v_user, v_project, 1, 'Lawsons', 'Materials', null, null, 'paid cap on tap watton card', 'Lawsons', null, '2025-11-21'::date, null, 1.0, 205.38, 0, 'Paid', 205.38, 205.38, 205.38, 'ledger'),
  (v_user, v_project, 1, 'Hauws Gray - Garden', 'Materials', null, null, 'Paid cash for bullnose garden etc', 'Hauws Gray - Garden', null, '2025-11-21'::date, 'Cash', 1.0, 500.0, 0, 'Paid', 500.0, 500.0, 500.0, 'ledger'),
  (v_user, v_project, 1, 'Distribution Tiles', 'Materials', null, null, 'Paid via shop', 'Distribution Tiles', null, '2025-11-21'::date, null, 1.0, 2221.98, 0, 'Paid', 2221.98, 2221.98, 2221.98, 'ledger'),
  (v_user, v_project, 1, 'Rest of bathroom - Various', 'Materials', null, null, 'Paid dad debit card', 'Rest of bathroom - Various', null, '2025-11-23'::date, 'Debit Card', 1.0, 3100.0, 0, 'Paid', 3100.0, 3100.0, 3100.0, 'ledger'),
  (v_user, v_project, 1, 'Lawsons', 'Materials', null, null, 'paid mama', 'Lawsons', null, '2025-11-24'::date, null, 1.0, 189.0, 0, 'Paid', 189.0, 189.0, 189.0, 'ledger'),
  (v_user, v_project, 1, 'George Davies Turf - Garden', 'Materials', null, null, 'Paid dad debit card', 'George Davies Turf - Garden', null, '2025-11-25'::date, 'Debit Card', 1.0, 586.2, 0, 'Paid', 586.2, 586.2, 586.2, 'ledger'),
  (v_user, v_project, 1, 'Tool Station', 'Materials', null, null, 'Cap on tap', 'Tool Station', null, '2025-11-26'::date, null, 1.0, 31.98, 0, 'Paid', 31.98, 31.98, 31.98, 'ledger'),
  (v_user, v_project, 1, 'Build BASE - Garden', 'Materials', null, null, 'Cap on tap', 'Build BASE - Garden', null, '2025-11-26'::date, null, 1.0, 132.0, 0, 'Paid', 132.0, 132.0, 132.0, 'ledger'),
  (v_user, v_project, 1, 'Pro Tiler', 'Materials', null, null, 'dad debit card', 'Pro Tiler', null, '2025-11-26'::date, 'Debit Card', 1.0, 1272.41, 0, 'Paid', 1272.41, 1272.41, 1272.41, 'ledger'),
  (v_user, v_project, 1, 'Clearence guys', 'Materials', null, null, 'Cash payment', 'Clearence guys', null, '2025-11-28'::date, 'Cash', 1.0, 650.0, 0, 'Paid', 650.0, 650.0, 650.0, 'ledger'),
  (v_user, v_project, 1, 'Plumbing', 'Materials', null, null, 'Cash payment', 'Plumbing', null, '2025-11-28'::date, 'Cash', 1.0, 3000.0, 0, 'Paid', 3000.0, 3000.0, 3000.0, 'ledger'),
  (v_user, v_project, 1, 'Eurocell', 'Materials', null, null, 'Cap on tap', 'Eurocell', null, '2025-11-28'::date, null, 1.0, 50.0, 0, 'Paid', 50.0, 50.0, 50.0, 'ledger'),
  (v_user, v_project, 1, 'welwyn skips', 'Materials', null, null, 'dad debit card', 'welwyn skips', null, '2025-12-01'::date, 'Debit Card', 1.0, 426.0, 0, 'Paid', 426.0, 426.0, 426.0, 'ledger'),
  (v_user, v_project, 1, 'Howdens', 'Materials', null, null, 'on account', 'Howdens', null, '2025-12-01'::date, null, 1.0, 1917.0, 0, 'Paid', 1917.0, 1917.0, 1917.0, 'ledger'),
  (v_user, v_project, 1, 'Lawsons', 'Materials', null, null, 'mama', 'Lawsons', null, '2025-12-02'::date, null, 1.0, 290.84, 0, 'Paid', 290.84, 290.84, 290.84, 'ledger'),
  (v_user, v_project, 1, 'Tops tiles', 'Materials', null, null, 'Cap on tap', 'Tops tiles', null, '2025-12-03'::date, null, 1.0, 131.16, 0, 'Paid', 131.16, 131.16, 131.16, 'ledger'),
  (v_user, v_project, 1, 'gills plumbing', 'Materials', null, null, 'sanj card', 'gills plumbing', null, '2025-12-05'::date, null, 1.0, 250.0, 0, 'Paid', 250.0, 250.0, 250.0, 'ledger'),
  (v_user, v_project, 1, 'Kitchen- Cabinets Direct', 'Materials', null, null, 'Cash payment', 'Kitchen- Cabinets Direct', null, '2025-12-05'::date, 'Cash', 1.0, 2000.0, 0, 'Paid', 2000.0, 2000.0, 2000.0, 'ledger'),
  (v_user, v_project, 1, 'Johnstones Paint', 'Materials', null, null, 'dad card', 'Johnstones Paint', null, '2025-12-08'::date, null, 1.0, 70.0, 0, 'Paid', 70.0, 70.0, 70.0, 'ledger'),
  (v_user, v_project, 1, 'AC Tools', 'Materials', null, null, 'Cash payment', 'AC Tools', null, '2025-12-09'::date, 'Cash', 1.0, 70.0, 0, 'Paid', 70.0, 70.0, 70.0, 'ledger'),
  (v_user, v_project, 1, 'George Davies Turf - Garden', 'Materials', null, null, 'dad debit card', 'George Davies Turf - Garden', null, '2025-12-12'::date, 'Debit Card', 1.0, 424.32, 0, 'Paid', 424.32, 424.32, 424.32, 'ledger'),
  (v_user, v_project, 1, 'Skips', 'Materials', null, null, 'dad debit card', 'Skips', null, '2025-12-12'::date, 'Debit Card', 1.0, 490.0, 0, 'Paid', 490.0, 490.0, 490.0, 'ledger'),
  (v_user, v_project, 1, 'Tiles - Trims etc', 'Materials', null, null, 'Cash payment', 'Tiles - Trims etc', null, '2025-12-12'::date, 'Cash', 1.0, 460.0, 0, 'Paid', 460.0, 460.0, 460.0, 'ledger'),
  (v_user, v_project, 1, 'Plumbing', 'Materials', null, null, 'Cash payment', 'Plumbing', null, '2025-12-12'::date, 'Cash', 1.0, 1000.0, 0, 'Paid', 1000.0, 1000.0, 1000.0, 'ledger'),
  (v_user, v_project, 1, 'Alspec Windows', 'Materials', null, null, 'Paid via invoices to shops', 'Alspec Windows', null, '2025-12-01'::date, null, 1.0, 2500.0, 0, 'Paid', 2500.0, 2500.0, 2500.0, 'ledger'),
  (v_user, v_project, 1, 'Distribution Tiles', 'Materials', null, null, 'Paid dad debit card', 'Distribution Tiles', null, '2025-12-15'::date, 'Debit Card', 1.0, 175.0, 0, 'Paid', 175.0, 175.0, 175.0, 'ledger'),
  (v_user, v_project, 1, 'Appliances Kitchen', 'Materials', null, null, 'Paid dad debit card', 'Appliances Kitchen', null, '2025-12-16'::date, 'Debit Card', 1.0, 2958.0, 0, 'Paid', 2958.0, 2958.0, 2958.0, 'ledger'),
  (v_user, v_project, 1, 'Johnstones Paint', 'Materials', null, null, 'Paid dad debit card', 'Johnstones Paint', null, '2025-12-16'::date, 'Debit Card', 1.0, 379.0, 0, 'Paid', 379.0, 379.0, 379.0, 'ledger'),
  (v_user, v_project, 1, 'Cawdor', 'Materials', null, null, 'Cash payment', 'Cawdor', null, '2025-12-17'::date, 'Cash', 1.0, 3450.0, 0, 'Paid', 3450.0, 3450.0, 3450.0, 'ledger'),
  (v_user, v_project, 1, 'Kitchen- Cabinets Direct', 'Materials', null, null, 'Cash payment', 'Kitchen- Cabinets Direct', null, '2025-12-17'::date, 'Cash', 1.0, 900.0, 0, 'Paid', 900.0, 900.0, 900.0, 'ledger'),
  (v_user, v_project, 1, 'Electrics', 'Materials', null, null, 'Cash payment', 'Electrics', null, '2025-12-22'::date, 'Cash', 1.0, 5130.0, 0, 'Paid', 5130.0, 5130.0, 5130.0, 'ledger'),
  (v_user, v_project, 1, 'Johnstones Paint', 'Materials', null, null, 'debit card dad', 'Johnstones Paint', null, '2025-12-22'::date, 'Debit Card', 1.0, 276.0, 0, 'Paid', 276.0, 276.0, 276.0, 'ledger'),
  (v_user, v_project, 1, 'Plumbing', 'Materials', null, null, 'Cash payment', 'Plumbing', null, '2025-12-24'::date, 'Cash', 1.0, 1500.0, 0, 'Paid', 1500.0, 1500.0, 1500.0, 'ledger'),
  (v_user, v_project, 1, 'Misc cupboard materials', 'Materials', null, null, 'Cash payment', 'Misc cupboard materials', null, '2026-01-09'::date, 'Cash', 1.0, 145.0, 0, 'Paid', 145.0, 145.0, 145.0, 'ledger'),
  (v_user, v_project, 1, 'Plumbing', 'Materials', null, null, 'Cash payment', 'Plumbing', null, '2026-01-09'::date, 'Cash', 1.0, 500.0, 0, 'Paid', 500.0, 500.0, 500.0, 'ledger'),
  (v_user, v_project, 1, 'Alspec Windows', 'Materials', null, null, 'Cash payment', 'Alspec Windows', null, '2026-01-09'::date, 'Cash', 1.0, 1000.0, 0, 'Paid', 1000.0, 1000.0, 1000.0, 'ledger'),
  (v_user, v_project, 1, 'Carpets', 'Materials', null, null, 'Cash payment', 'Carpets', null, '2026-01-09'::date, 'Cash', 1.0, 900.0, 0, 'Paid', 900.0, 900.0, 900.0, 'ledger'),
  (v_user, v_project, 1, 'Alspec Windows', 'Materials', null, null, 'to be paid', 'Alspec Windows', null, '2026-01-25'::date, null, 1.0, 1500.0, 0, 'Paid', 1500.0, 1500.0, 1500.0, 'ledger'),
  (v_user, v_project, 1, 'Staging', 'Materials', null, null, 'paid', 'Staging', null, '2026-01-14'::date, null, 1.0, 2225.0, 0, 'Paid', 2225.0, 2225.0, 2225.0, 'ledger'),
  (v_user, v_project, 1, 'Driveway Clean + front garden cleared', 'Materials', null, null, 'Kevin', 'Driveway Clean + front garden cleared', null, '2026-01-14'::date, null, 1.0, 140.0, 0, 'Paid', 140.0, 140.0, 140.0, 'ledger'),
  (v_user, v_project, 1, 'Mastic Man', 'Materials', null, null, 'Cash payment', 'Mastic Man', null, '2026-01-16'::date, 'Cash', 1.0, 100.0, 0, 'Paid', 100.0, 100.0, 100.0, 'ledger'),
  (v_user, v_project, 1, 'Plumbing', 'Materials', null, null, 'Cash payment', 'Plumbing', null, '2026-01-24'::date, 'Cash', 1.0, 1000.0, 0, 'Paid', 1000.0, 1000.0, 1000.0, 'ledger');

  insert into public.trade_lookups (user_id, name, default_rate, default_markup_pct) values
  (v_user, 'General Builder', 45.0, 10.0),
  (v_user, 'Carpenter/Joiner', 50.0, 10.0),
  (v_user, 'Plumber', 60.0, 10.0),
  (v_user, 'Electrician', 65.0, 10.0),
  (v_user, 'Plasterer', 55.0, 10.0),
  (v_user, 'Tiler', 55.0, 10.0),
  (v_user, 'Decorator', 45.0, 10.0),
  (v_user, 'Roofer', 60.0, 10.0),
  (v_user, 'Groundworker', 55.0, 10.0),
  (v_user, 'Kitchen Fitter', 55.0, 10.0),
  (v_user, 'Bathroom Fitter', 55.0, 10.0),
  (v_user, 'Glazier', 55.0, 10.0),
  (v_user, 'Scaffolder', 55.0, 10.0),
  (v_user, 'Flooring Installer', 50.0, 10.0),
  (v_user, 'Skip/Disposal', 0.0, 0.0),
  (v_user, 'Other', 50.0, 10.0)
  on conflict (user_id, name) do update
    set default_rate = excluded.default_rate,
        default_markup_pct = excluded.default_markup_pct;

  insert into public.project_weeks (user_id, project_id, week_number, completion_pct)
  select v_user, v_project, generate_series(1, 15), 0
  on conflict (project_id, week_number) do nothing;

  raise notice 'Imported project % for user %', v_project, v_user;
end $$;

-- Verify before committing.
select p.name, p.target_budget,
       count(*) filter (where e.source = 'diary')  as diary_rows,
       count(*) filter (where e.source = 'ledger') as ledger_rows,
       sum(e.actual_amount) as total_actual
from public.projects p
join public.expense_entries e on e.project_id = p.id
where p.user_id = '5d3fc9ff-92a3-4923-a18b-7eb5eade3105'
group by p.name, p.target_budget;

commit;
-- rollback;  -- use instead of commit if the numbers look wrong
