-- RenovaTrack — mark the diary rows that the spreadsheet shows as paid.
-- GENERATED by scripts/gen_mark_paid_sql.py — do not hand-edit.
--
-- Why: File 1's 'Week-by-Week Plan' has 'Planned' in the Status column on all
-- 40 rows — the sheet never sets it. What actually records a payment is the
-- 'Paid Date' column, filled on 20 rows (weeks 1-7). 0005 imported the
-- literal Status, so every row landed as Planned and Paid to Date showed £0.00.
--
-- The dates are hand-typed day/month with a weekday and no year ('Friday 27/2').
-- Every one falls on the stated weekday only in 2026, so the year is resolved
-- from the weekday rather than assumed.
--
-- Idempotent: re-running changes nothing. Also a no-op after re-running an
-- up-to-date 0005, which now applies the same rule at import time.
--
-- Run in the Supabase SQL editor, after 0005.

begin;

do $$
declare
  v_user    uuid := '5d3fc9ff-92a3-4923-a18b-7eb5eade3105';
  v_project uuid;
  v_rows    int;
begin
  select id into v_project
  from public.projects
  where user_id = v_user and name = '46 Glenferrie Road';

  if v_project is null then
    raise exception 'Project % not found for user % — run 0005 first.',
      '46 Glenferrie Road', v_user;
  end if;

  with paid(week_number, description, quoted_amount, paid_date) as (
    values
    (1, 'Labourers', 450.0, '2026-02-27'::date),
    (1, 'DMC - Dave', 220.0, '2026-02-27'::date),
    (1, 'Adam - Clearance', 1100.0, '2026-02-27'::date),
    (2, 'Labourers', 675.0, '2026-03-06'::date),
    (2, 'Adam - Clearance', 1000.0, '2026-03-06'::date),
    (3, 'Labourers', 525.0, '2026-03-13'::date),
    (4, 'Labourers', 450.0, '2026-03-20'::date),
    (4, 'Adam - Clearance', 1100.0, '2026-03-20'::date),
    (5, 'Skip', 480.0, '2026-03-27'::date),
    (5, 'Labourers', 450.0, '2026-03-27'::date),
    (5, 'Dave Barker (Groundwork)', 1250.0, '2026-03-27'::date),
    (5, 'Master Mix', 1025.0, '2026-03-27'::date),
    (6, 'Labourers', 300.0, '2026-04-03'::date),
    (6, 'Dave Barker (Groundwork)', 900.0, '2026-04-03'::date),
    (6, 'Dave Builder', 300.0, '2026-04-03'::date),
    (6, 'Steels', 1000.0, '2026-04-03'::date),
    (7, 'SDE Drainage', 98.4, '2026-04-10'::date),
    (7, 'Master Mix', 900.0, '2026-04-10'::date),
    (7, 'Labourers', 450.0, '2026-04-10'::date),
    (7, 'Dave', 600.0, '2026-04-10'::date)
  )
  update public.expense_entries e
  set status      = 'Paid',
      paid_amount = e.actual_amount,
      paid_date   = p.paid_date,
      -- The free-text date note exists only because paid_date could not hold
      -- it. Now that it can, drop the marker and tidy any stranded separator.
      notes = nullif(btrim(
                -- 2. re-normalise the ' | ' separators the cut may have left ragged
                regexp_replace(
                  -- 1. drop the marker and the separator in front of it
                  regexp_replace(coalesce(e.notes, ''),
                                 '\s*\|?\s*Paid date \(as written\):[^|]*', '', 'g'),
                  '\s*\|\s*', ' | ', 'g'),
                ' |'), '')
  from paid p
  where e.project_id    = v_project
    and e.source        = 'diary'
    and e.week_number   = p.week_number
    and e.description   = p.description
    and e.quoted_amount = p.quoted_amount;

  get diagnostics v_rows = row_count;
  raise notice 'Marked % diary rows as Paid (expected 20).', v_rows;

  if v_rows <> 20 then
    raise exception 'Expected to update 20 rows but updated % — aborting.', v_rows;
  end if;
end $$;

-- Verify before committing. Expect: 20 paid rows, paid_total 13273.4,
-- and 0 rows left carrying the old free-text date note.
select count(*) filter (where status = 'Paid')                     as paid_rows,
       count(*) filter (where status = 'Planned')                  as planned_rows,
       sum(paid_amount)                                            as paid_total,
       count(*) filter (where notes like '%Paid date (as written)%') as stale_notes
from public.expense_entries
where source = 'diary'
  and project_id = (select id from public.projects
                    where user_id = '5d3fc9ff-92a3-4923-a18b-7eb5eade3105' and name = '46 Glenferrie Road');

commit;
-- rollback;  -- use instead of commit if the numbers look wrong
