-- ####################################################################
-- ##  SUPERSEDED BY 0009_reimport_file1_only.sql — DO NOT RUN THIS.  ##
-- ####################################################################
--
-- Retired 2026-08-14. This file imported Renovation_Cost_Tracker-1.xlsx as
-- 96 'ledger' rows. That workbook is a DIFFERENT JOB — it names no address,
-- its dates (2025-11-02 to 2026-01-25) stop a month before this project's
-- week 1, and it ends with carpets and staging while week 1 here is
-- 'clearance / back to brick'.
--
-- It also broke the Price Tracker: its 'Materials & Suppliers' sheet is a
-- payment log whose Unit Cost column holds the amount of each instalment
-- (Item blank and Quantity 1 on all 60 rows). A 416.05 deposit followed by
-- a 3,586.00 balance to Wunda UFH therefore read as a 761.9% price rise,
-- and ten other suppliers did the same thing.
--
-- 0009 rebuilds from 46_Glenferrie_Rd_..._Updated.xlsx alone. Running THIS
-- file again would put the other job's 96 rows straight back.
--
-- ####################################################################
--
-- RenovaTrack — reimport the Week-by-Week Plan, now covering weeks 1-23.
-- GENERATED by scripts/build_import_sql.py — do not hand-edit.
--
-- Owner  : 5d3fc9ff-92a3-4923-a18b-7eb5eade3105 (admin@pk.com)
-- Diary  : 111 rows, weeks 1-23  (File 1, 'Week-by-Week Plan')
-- Ledger : 96 rows                (File 2, unchanged)
-- Trades : 16 lookups
--
-- Supersedes 0005 (weeks 1-15) and 0006 (mark-paid). Do NOT run those
-- again — this file rebuilds the project from scratch and already sets
-- the Paid status on every row that has a paid date.
--
-- Money mapping — actual_amount is EX-VAT because the app derives
--   total_incl_vat = actual_amount x (1 + vat_rate/100)
-- on every read (lib/calculations.ts). Storing an incl-VAT figure here
-- is what made the old import show VAT twice.
--   actual_amount = Labour Cost + Materials Cost   (ex-VAT)
--   quoted_amount = Total incl. VAT                (the sheet's forecast)
--   paid_amount   = Total incl. VAT, when a Paid Date is filled
--
-- After this runs the Overview tab should read:
--   Total Quoted      £151,644.78
--   Actual Total      £151,644.78   (= the sheet's Forecast Total)
--   Variance vs Quote £-0.00
--   Paid to Date      £13,273.40   (= the sheet's 'Paid to date')
--   Remaining to Pay  £138,371.38  (= the sheet's 'Committed')
--   Weeks Tracked     23
--
-- Run in the Supabase SQL editor. Re-runnable: it deletes this user's
-- existing copy of the project first. It refuses to commit if any week
-- total disagrees with the spreadsheet.

begin;

do $$
declare
  v_user    uuid := '5d3fc9ff-92a3-4923-a18b-7eb5eade3105';
  v_project uuid;
begin
  if not exists (select 1 from auth.users where id = v_user) then
    raise exception 'User % not found in auth.users.', v_user;
  end if;

  -- Idempotency: clear any prior import of this project.
  delete from public.projects where user_id = v_user and name = '46 Glenferrie Road';

  insert into public.projects (user_id, name, target_budget, status, notes)
  values (v_user, '46 Glenferrie Road', 98932.12, 'active',
          'Imported from the Week-by-Week Plan, weeks 1-23.')
  returning id into v_project;

  insert into public.expense_entries (user_id, project_id, week_number, description, category, trade, location_room, notes, supplier, invoice_ref, paid_date, payment_method, qty, unit_cost, vat_rate, status, quoted_amount, actual_amount, paid_amount, source) values
  (v_user, v_project, 1, 'Labourers', 'Labour', 'General Builder', null, 'Clearence - 6 man days | Rate: 45.0', null, null, '2026-02-27'::date, 'Cash', 0, 0, 0, 'Paid', 450.0, 450.0, 450.0, 'diary'),
  (v_user, v_project, 1, 'DMC - Dave', 'Labour', 'General Builder', null, 'Dave first day on site | Rate: 45.0', null, null, '2026-02-27'::date, 'Cash', 0, 0, 0, 'Paid', 220.0, 220.0, 220.0, 'diary'),
  (v_user, v_project, 1, 'Adam - Clearance', 'Labour', 'Skip/Disposal', null, 'Rubbish Removal', null, null, '2026-02-27'::date, 'Cash', 0, 0, 0, 'Paid', 1100.0, 1100.0, 1100.0, 'diary'),
  (v_user, v_project, 2, 'Labourers', 'Labour', 'General Builder', null, 'Clearence / back to brick - 9 d | Rate: 45.0', null, null, '2026-03-06'::date, 'Cash', 0, 0, 0, 'Paid', 675.0, 675.0, 675.0, 'diary'),
  (v_user, v_project, 2, 'Adam - Clearance', 'Labour', 'Skip/Disposal', null, 'Rubbish Removal', null, null, '2026-03-06'::date, 'Cash', 0, 0, 0, 'Paid', 1000.0, 1000.0, 1000.0, 'diary'),
  (v_user, v_project, 3, 'Labourers', 'Labour', 'General Builder', null, 'Clearence / back to brick - 7 d | Rate: 45.0', null, null, '2026-03-13'::date, 'Cash', 0, 0, 0, 'Paid', 525.0, 525.0, 525.0, 'diary'),
  (v_user, v_project, 4, 'Labourers', 'Labour', 'General Builder', null, 'Clearance 6d | Rate: 45.0', null, null, '2026-03-20'::date, 'Cash', 0, 0, 0, 'Paid', 450.0, 450.0, 450.0, 'diary'),
  (v_user, v_project, 4, 'Adam - Clearance', 'Labour', 'Skip/Disposal', null, null, null, null, '2026-03-20'::date, 'Cash', 0, 0, 0, 'Paid', 1100.0, 1100.0, 1100.0, 'diary'),
  (v_user, v_project, 5, 'Skip', 'Labour', 'Skip/Disposal', null, null, 'Stevenage Skips', null, '2026-03-27'::date, 'Cash', 0, 0, 0, 'Paid', 480.0, 480.0, 480.0, 'diary'),
  (v_user, v_project, 5, 'Labourers', 'Labour', 'General Builder', null, 'Rate: 45.0', null, null, '2026-03-27'::date, 'Cash', 0, 0, 0, 'Paid', 450.0, 450.0, 450.0, 'diary'),
  (v_user, v_project, 5, 'Dave Barker (Groundwork)', 'Labour', 'General Builder', null, 'Rate: 45.0', null, null, '2026-03-27'::date, 'Cash', 0, 0, 0, 'Paid', 1250.0, 1250.0, 1250.0, 'diary'),
  (v_user, v_project, 5, 'Master Mix', 'Materials', 'Other', null, 'Rate: 50.0', null, null, '2026-03-27'::date, 'Debit Card', 0, 0, 0, 'Paid', 1025.0, 1025.0, 1025.0, 'diary'),
  (v_user, v_project, 6, 'Labourers', 'Labour', 'General Builder', null, 'Rate: 45.0', null, null, '2026-04-03'::date, 'Cash', 0, 0, 0, 'Paid', 300.0, 300.0, 300.0, 'diary'),
  (v_user, v_project, 6, 'Dave Barker (Groundwork)', 'Labour', 'General Builder', null, 'Rate: 45.0', null, null, '2026-04-03'::date, 'Cash', 0, 0, 0, 'Paid', 900.0, 900.0, 900.0, 'diary'),
  (v_user, v_project, 6, 'Dave Builder', 'Labour', 'General Builder', null, 'Rate: 45.0', null, null, '2026-04-03'::date, 'Cash', 0, 0, 0, 'Paid', 300.0, 300.0, 300.0, 'diary'),
  (v_user, v_project, 6, 'Steels', 'Materials', 'General Builder', null, 'Rate: 45.0', null, null, '2026-04-03'::date, 'Cash', 0, 0, 0, 'Paid', 1000.0, 1000.0, 1000.0, 'diary'),
  (v_user, v_project, 7, 'SDE Drainage', 'Materials', 'General Builder', null, 'Rate: 45.0', null, null, '2026-04-10'::date, 'Credit Card', 0, 0, 20, 'Paid', 98.4, 82.0, 98.4, 'diary'),
  (v_user, v_project, 7, 'Master Mix', 'Materials', 'General Builder', null, 'Rate: 45.0', null, null, '2026-04-10'::date, 'Debit Card', 0, 0, 20, 'Paid', 900.0, 750.0, 900.0, 'diary'),
  (v_user, v_project, 7, 'Labourers', 'Labour', 'General Builder', null, 'Rate: 45.0', null, null, '2026-04-10'::date, 'Cash', 0, 0, 0, 'Paid', 450.0, 450.0, 450.0, 'diary'),
  (v_user, v_project, 7, 'Dave', 'Labour', 'General Builder', null, 'Rate: 45.0', '£300 PAID FROM OWED', null, '2026-04-10'::date, 'Cash', 0, 0, 0, 'Paid', 600.0, 600.0, 600.0, 'diary'),
  (v_user, v_project, 8, 'dave', 'Labour', 'General Builder', null, 'Rate: 45.0', '£400 paid from whats owed', null, null, null, 0, 0, 0, 'Planned', 1400.0, 1400.0, 0, 'diary'),
  (v_user, v_project, 8, 'Labourers', 'Labour', 'General Builder', null, 'Rate: 45.0', null, null, null, null, 0, 0, 0, 'Planned', 750.0, 750.0, 0, 'diary'),
  (v_user, v_project, 8, 'Owen Brickwork', 'Labour', 'General Builder', null, 'Rate: 45.0', '1 day - to DPC', null, null, null, 0, 0, 0, 'Planned', 275.0, 275.0, 0, 'diary'),
  (v_user, v_project, 9, 'Owen Brickwork', 'Labour', 'General Builder', null, 'Rate: 45.0', 'all brickwork completed', null, null, null, 0, 0, 0, 'Planned', 1935.0, 1935.0, 0, 'diary'),
  (v_user, v_project, 9, 'Dave Builder', 'Labour', 'General Builder', null, 'Rate: 45.0', 'steels in', null, null, null, 0, 0, 0, 'Planned', 2035.0, 2035.0, 0, 'diary'),
  (v_user, v_project, 9, 'Labourers', 'Labour', 'General Builder', null, 'Rate: 45.0', 'steels help plus disposal', null, null, null, 0, 0, 0, 'Planned', 900.0, 900.0, 0, 'diary'),
  (v_user, v_project, 9, 'Toby', 'Labour', 'Skip/Disposal', null, null, 'Toby cleared out huge earth pile', null, null, null, 0, 0, 0, 'Planned', 1240.0, 1240.0, 0, 'diary'),
  (v_user, v_project, 10, 'Dave Builder', 'Labour', 'General Builder', null, 'Rate: 45.0', null, null, null, null, 0, 0, 0, 'Planned', 1640.0, 1640.0, 0, 'diary'),
  (v_user, v_project, 10, 'Owen Brickwork', 'Labour', 'General Builder', null, 'Rate: 45.0', null, null, null, null, 0, 0, 0, 'Planned', 675.0, 675.0, 0, 'diary'),
  (v_user, v_project, 10, 'Labourers', 'Labour', 'General Builder', null, 'Rate: 45.0', null, null, null, null, 0, 0, 0, 'Planned', 600.0, 600.0, 0, 'diary'),
  (v_user, v_project, 11, 'Dave Builder', 'Labour', 'General Builder', null, 'Rate: 45.0', null, null, null, null, 0, 0, 0, 'Planned', 400.0, 400.0, 0, 'diary'),
  (v_user, v_project, 11, 'Labourers', 'Labour', 'General Builder', null, 'Rate: 45.0', null, null, null, null, 0, 0, 0, 'Planned', 300.0, 300.0, 0, 'diary'),
  (v_user, v_project, 12, 'Scaffold', 'Materials', 'Scaffolder', null, 'Rate: 55.0', null, null, null, null, 0, 0, 0, 'Planned', 1000.0, 1000.0, 0, 'diary'),
  (v_user, v_project, 12, 'Nick Loft', 'Labour', 'General Builder', null, 'Rate: 45.0', null, null, null, null, 0, 0, 0, 'Planned', 3000.0, 3000.0, 0, 'diary'),
  (v_user, v_project, 13, 'Labourers', 'Labour', 'General Builder', null, 'Rate: 45.0', null, null, null, null, 0, 0, 0, 'Planned', 300.0, 300.0, 0, 'diary'),
  (v_user, v_project, 13, 'Adam - Clearance', 'Labour', 'Skip/Disposal', null, null, null, null, null, null, 0, 0, 0, 'Planned', 275.0, 275.0, 0, 'diary'),
  (v_user, v_project, 13, 'Nick Loft', 'Labour', 'General Builder', null, 'Rate: 45.0', null, null, null, null, 0, 0, 0, 'Planned', 2000.0, 2000.0, 0, 'diary'),
  (v_user, v_project, 14, 'Nick Loft', null, null, null, null, null, null, null, null, 0, 0, 0, 'Planned', 2520.0, 2520.0, 0, 'diary'),
  (v_user, v_project, 15, 'Nick Loft', 'Labour', 'General Builder', null, 'Rate: 45.0', null, null, null, null, 0, 0, 0, 'Planned', 2520.0, 2520.0, 0, 'diary'),
  (v_user, v_project, 15, 'Lawsons', 'Materials', 'Other', null, 'Rate: 50.0', null, null, null, null, 0, 0, 20, 'Planned', 5373.41, 4477.84, 0, 'diary'),
  (v_user, v_project, 16, 'Eurocell', 'Materials', 'General Builder', null, 'Rate: 45.0', null, null, null, null, 0, 0, 20, 'Planned', 201.29, 167.74, 0, 'diary'),
  (v_user, v_project, 16, 'Wunda UFH Materials', 'Materials', 'General Builder', null, 'Rate: 45.0', null, null, null, null, 0, 0, 20, 'Planned', 600.59, 500.49, 0, 'diary'),
  (v_user, v_project, 16, 'Cabinets Direct (Kitchen)', 'Materials', 'General Builder', null, 'Rate: 45.0', null, null, null, null, 0, 0, 20, 'Planned', 5000.0, 4166.67, 0, 'diary'),
  (v_user, v_project, 16, 'Alspec Windows', 'Materials', 'Glazier', null, 'Rate: 55.0', null, null, null, null, 0, 0, 20, 'Planned', 8786.4, 7322.0, 0, 'diary'),
  (v_user, v_project, 16, 'Dave Builder', 'Labour', 'General Builder', null, 'Rate: 45.0', null, null, null, null, 0, 0, 20, 'Planned', 750.0, 625.0, 0, 'diary'),
  (v_user, v_project, 16, 'Owen Brickwork', 'Labour', 'General Builder', null, 'REPOINTING PLUS OTHER BITS | Rate: 45.0', null, null, null, null, 0, 0, 20, 'Planned', 560.0, 466.67, 0, 'diary'),
  (v_user, v_project, 16, 'Nick Loft', 'Labour', 'General Builder', null, 'Rate: 45.0', null, null, null, null, 0, 0, 20, 'Planned', 2520.0, 2100.0, 0, 'diary'),
  (v_user, v_project, 17, 'Miscl Roofing Materials', 'Materials', 'Roofer', null, 'Lead, Felt, Nails | Rate: 60.0', null, null, null, null, 0, 0, 20, 'Planned', 3145.42, 2621.18, 0, 'diary'),
  (v_user, v_project, 17, 'Sagar Roofing', 'Labour', 'Roofer', null, '£150-£180 per day to note | Rate: 60.0', null, null, null, null, 0, 0, 20, 'Planned', 2400.0, 2000.0, 0, 'diary'),
  (v_user, v_project, 17, 'Travis Perkins', 'Materials', 'General Builder', null, 'Brick repointing materials | Rate: 45.0', null, null, null, null, 0, 0, 20, 'Planned', 237.41, 197.84, 0, 'diary'),
  (v_user, v_project, 17, 'Eurocell', 'Materials', 'Roofer', null, 'Fascias / soffits / gutters | Rate: 60.0', null, null, null, null, 0, 0, 20, 'Planned', 284.86, 237.38, 0, 'diary'),
  (v_user, v_project, 17, 'Nick Loft', 'Labour', 'General Builder', null, 'Rate: 45.0', null, null, null, null, 0, 0, 20, 'Planned', 2520.0, 2100.0, 0, 'diary'),
  (v_user, v_project, 17, 'CAD Stairs', 'Materials', null, null, '50% DEPOSIT', null, null, null, null, 0, 0, 20, 'Planned', 1500.0, 1250.0, 0, 'diary'),
  (v_user, v_project, 17, 'St Albans Bathroom Centre', 'Materials', 'Bathroom Fitter', null, '50% DEPOSIT | Rate: 55.0', null, null, null, null, 0, 0, 20, 'Planned', 4850.0, 4041.67, 0, 'diary'),
  (v_user, v_project, 17, 'Labourers', 'Labour', 'General Builder', null, '3 weeks of labour | Rate: 45.0', null, null, null, null, 0, 0, 20, 'Planned', 1350.0, 1125.0, 0, 'diary'),
  (v_user, v_project, 18, 'Saris', 'Materials', 'Glazier', null, 'Skylight inc upstand | Rate: 55.0', null, null, null, null, 0, 0, 20, 'Planned', 808.08, 673.4, 0, 'diary'),
  (v_user, v_project, 18, 'Sagar Roofing', 'Labour', 'Roofer', null, 'Rate: 60.0', null, null, null, null, 0, 0, 20, 'Planned', 600.0, 500.0, 0, 'diary'),
  (v_user, v_project, 18, 'Todds Doors', 'Materials', 'Carpenter/Joiner', null, 'Fire rated pocket door | Rate: 50.0', null, null, null, null, 0, 0, 20, 'Planned', 742.5, 618.75, 0, 'diary'),
  (v_user, v_project, 18, 'Ryan Steels', 'Materials', null, null, 'Part payment Steels', null, null, null, null, 0, 0, 20, 'Planned', 1370.0, 1141.67, 0, 'diary'),
  (v_user, v_project, 18, 'Eaves Electrical', 'Materials', 'Electrician', null, 'part payment 1st fix | Rate: 65.0', null, null, null, null, 0, 0, 20, 'Planned', 3105.0, 2587.5, 0, 'diary'),
  (v_user, v_project, 18, 'Lawsons', 'Materials', 'General Builder', null, 'Paid via AMEX | Rate: 45.0', null, null, null, null, 0, 0, 0, 'Planned', 4035.65, 4035.65, 0, 'diary'),
  (v_user, v_project, 18, 'Owen Brickwork', 'Labour', null, null, 'Chimney work plus other bits', null, null, null, null, 0, 0, 20, 'Planned', 425.0, 354.17, 0, 'diary'),
  (v_user, v_project, 18, 'Dave Builder', 'Labour', 'General Builder', null, 'Screed / GF WORKS CARPENTRY | Rate: 45.0', null, null, null, null, 0, 0, 20, 'Planned', 1600.0, 1333.33, 0, 'diary'),
  (v_user, v_project, 19, 'CAD Stairs', 'Materials', 'General Builder', null, 'Rate: 45.0', null, null, null, null, 0, 0, 20, 'Planned', 1500.0, 1250.0, 0, 'diary'),
  (v_user, v_project, 19, 'Johnstones Paint', 'Materials', 'Other', null, 'Exterior Paint | Rate: 50.0', null, null, null, null, 0, 0, 20, 'Planned', 97.36, 81.13, 0, 'diary'),
  (v_user, v_project, 19, 'JJ Roofing', 'Materials', 'Roofer', null, 'Flat roof GF Materials | Rate: 60.0', null, null, null, null, 0, 0, 20, 'Planned', 1250.0, 1041.67, 0, 'diary'),
  (v_user, v_project, 19, 'Nick Loft', 'Labour', 'General Builder', null, 'Final payment nick | Rate: 45.0', null, null, null, null, 0, 0, 20, 'Planned', 1530.0, 1275.0, 0, 'diary'),
  (v_user, v_project, 19, 'Jewsons', 'Materials', 'General Builder', null, 'Drywall Adhesive | Rate: 45.0', null, null, null, null, 0, 0, 20, 'Planned', 471.6, 393.0, 0, 'diary'),
  (v_user, v_project, 19, 'Dave Builder', 'Labour', 'General Builder', null, 'Insulation in loft and other bits | Rate: 45.0', null, null, null, null, 0, 0, 20, 'Planned', 1500.0, 1250.0, 0, 'diary'),
  (v_user, v_project, 19, 'Sagar Roofing', 'Labour', 'Roofer', null, 'GF | Rate: 60.0', null, null, null, null, 0, 0, 20, 'Planned', 500.0, 416.67, 0, 'diary'),
  (v_user, v_project, 19, 'Labourers', 'Labour', 'General Builder', null, '2 weeks | Rate: 45.0', null, null, null, null, 0, 0, 20, 'Planned', 1440.0, 1200.0, 0, 'diary'),
  (v_user, v_project, 19, 'A1 Skips', 'Labour', 'Skip/Disposal', null, '2 skips', null, null, null, null, 0, 0, 20, 'Planned', 580.0, 483.33, 0, 'diary'),
  (v_user, v_project, 19, 'Adam - Clearance', 'Labour', 'Skip/Disposal', null, '2 loads van clearence', null, null, null, null, 0, 0, 20, 'Planned', 400.0, 333.33, 0, 'diary'),
  (v_user, v_project, 19, 'Owen Brickwork', 'Labour', 'General Builder', null, '2 DAYS FINISHING GROUND FLLOR | Rate: 45.0', null, null, null, null, 0, 0, 20, 'Planned', 750.0, 625.0, 0, 'diary'),
  (v_user, v_project, 20, 'Ryan Steels', 'Materials', 'General Builder', null, 'Final Steels | Rate: 45.0', null, null, null, null, 0, 0, 0, 'Planned', 1000.0, 1000.0, 0, 'diary'),
  (v_user, v_project, 20, 'Watts Roofing', 'Materials', null, null, 'Roofing materials', null, null, null, null, 0, 0, 0, 'Planned', 337.5, 337.5, 0, 'diary'),
  (v_user, v_project, 20, 'Pro Tiler', 'Materials', null, null, 'UFH EN SUITE', null, null, null, null, 0, 0, 0, 'Planned', 773.25, 773.25, 0, 'diary'),
  (v_user, v_project, 20, 'Dave Builder', 'Labour', null, null, null, null, null, null, null, 0, 0, 0, 'Planned', 2000.0, 2000.0, 0, 'diary'),
  (v_user, v_project, 20, 'Skips', 'Materials', null, null, null, null, null, null, null, 0, 0, 0, 'Planned', 290.0, 290.0, 0, 'diary'),
  (v_user, v_project, 20, 'Labourers', 'Labour', null, null, null, null, null, null, null, 0, 0, 0, 'Planned', 530.0, 530.0, 0, 'diary'),
  (v_user, v_project, 21, 'Roofers', 'Labour', null, null, '£400 materials of this amount', null, null, null, null, 0, 0, 0, 'Planned', 1800.0, 1800.0, 0, 'diary'),
  (v_user, v_project, 21, 'Cut Price Tiles', 'Materials', null, null, 'Deposit', null, null, null, null, 0, 0, 0, 'Planned', 200.0, 200.0, 0, 'diary'),
  (v_user, v_project, 21, 'Plastic Construction', 'Materials', null, null, 'Gutter materials', null, null, null, null, 0, 0, 0, 'Planned', 110.0, 110.0, 0, 'diary'),
  (v_user, v_project, 21, 'Pro Tiler', 'Materials', null, null, 'Tile Materials', null, null, null, null, 0, 0, 0, 'Planned', 423.79, 423.79, 0, 'diary'),
  (v_user, v_project, 21, 'Scaffold', 'Materials', null, null, 'Final payment', null, null, null, null, 0, 0, 0, 'Planned', 500.0, 500.0, 0, 'diary'),
  (v_user, v_project, 21, 'Dave Builder', 'Labour', null, null, null, null, null, null, null, 0, 0, 0, 'Planned', 1475.0, 1475.0, 0, 'diary'),
  (v_user, v_project, 21, 'Paint', 'Labour', null, null, 'Painting outside', null, null, null, null, 0, 0, 0, 'Planned', 170.0, 170.0, 0, 'diary'),
  (v_user, v_project, 21, 'Owen Brickwork', 'Labour', null, null, 'repointing', null, null, null, null, 0, 0, 0, 'Planned', 710.0, 710.0, 0, 'diary'),
  (v_user, v_project, 22, 'Todds Doors', 'Materials', null, null, 'Doors and hinges', null, null, null, null, 0, 0, 0, 'Planned', 1595.4, 1595.4, 0, 'diary'),
  (v_user, v_project, 22, 'Cut Price Tiles', 'Materials', null, null, 'Tiles for bathrooms', null, null, null, null, 0, 0, 0, 'Planned', 1270.56, 1270.56, 0, 'diary'),
  (v_user, v_project, 22, 'Alspec Windows', 'Materials', null, null, 'Windows (£2k left)', null, null, null, null, 0, 0, 0, 'Planned', 4686.4, 4686.4, 0, 'diary'),
  (v_user, v_project, 22, 'Metres Direct LTD', 'Materials', null, null, 'Skirt + Architrave', null, null, null, null, 0, 0, 0, 'Planned', 1080.0, 1080.0, 0, 'diary'),
  (v_user, v_project, 22, 'Plasterers', 'Labour', null, null, '£5500 for house', null, null, null, null, 0, 0, 0, 'Planned', 2000.0, 2000.0, 0, 'diary'),
  (v_user, v_project, 22, 'Dryline - Boarding - Zoli', 'Labour', null, null, '£4000 for house', null, null, null, null, 0, 0, 0, 'Planned', 1500.0, 1500.0, 0, 'diary'),
  (v_user, v_project, 22, 'Corston', 'Materials', null, null, 'Handles, Locks', null, null, null, null, 0, 0, 0, 'Planned', 1049.88, 1049.88, 0, 'diary'),
  (v_user, v_project, 22, 'Dave Builder', 'Labour', null, null, '£135 materials', null, null, null, null, 0, 0, 0, 'Planned', 1135.0, 1135.0, 0, 'diary'),
  (v_user, v_project, 22, 'Lionvest', 'Materials', null, null, 'Wood Flooring - 80m2', null, null, null, null, 0, 0, 0, 'Planned', 3050.78, 3050.78, 0, 'diary'),
  (v_user, v_project, 22, 'Metres Direct LTD', 'Materials', null, null, 'Panelling / architrave/ picture rail', null, null, null, null, 0, 0, 0, 'Planned', 838.8, 838.8, 0, 'diary'),
  (v_user, v_project, 22, 'Topps Tiles', 'Materials', null, null, null, null, null, null, null, 0, 0, 0, 'Planned', 165.0, 165.0, 0, 'diary'),
  (v_user, v_project, 22, 'Adam - Clearance', 'Labour', null, null, null, null, null, null, null, 0, 0, 0, 'Planned', 200.0, 200.0, 0, 'diary'),
  (v_user, v_project, 23, 'ML Roofing', 'Labour', null, null, 'Lead work', null, null, null, null, 0, 0, 0, 'Planned', 150.0, 150.0, 0, 'diary'),
  (v_user, v_project, 23, 'AC Supplies', 'Materials', null, null, 'Jobs Screws etc from AC', null, null, null, null, 0, 0, 0, 'Planned', 1035.0, 1035.0, 0, 'diary'),
  (v_user, v_project, 23, 'Topps Tiles', 'Materials', null, null, null, null, null, null, null, 0, 0, 0, 'Planned', 69.23, 69.23, 0, 'diary'),
  (v_user, v_project, 23, 'Lawsons', 'Materials', null, null, 'June Invoices', null, null, null, null, 0, 0, 0, 'Planned', 11222.63, 11222.63, 0, 'diary'),
  (v_user, v_project, 23, 'Pete Tiles', 'Labour', null, null, 'Bathroom tile plus wood floor', null, null, null, null, 0, 0, 0, 'Planned', 1420.0, 1420.0, 0, 'diary'),
  (v_user, v_project, 23, 'Plasterers', 'Labour', null, null, null, null, null, null, null, 0, 0, 0, 'Planned', 2000.0, 2000.0, 0, 'diary'),
  (v_user, v_project, 23, 'dryliner- zoli', 'Labour', null, null, null, null, null, null, null, 0, 0, 0, 'Planned', 1000.0, 1000.0, 0, 'diary'),
  (v_user, v_project, 23, 'Johnstones', 'Materials', null, null, 'Paint Ensuite plus 1st floor some of it', null, null, null, null, 0, 0, 0, 'Planned', 199.34, 199.34, 0, 'diary'),
  (v_user, v_project, 23, 'Maciekh', 'Labour', null, null, '2nd fix carpentry- 2nd floor', null, null, null, null, 0, 0, 0, 'Planned', 800.0, 800.0, 0, 'diary'),
  (v_user, v_project, 23, 'Mark Cornice', 'Materials', null, null, 'cornice supply and install', null, null, null, null, 0, 0, 0, 'Planned', 2924.25, 2924.25, 0, 'diary'),
  (v_user, v_project, 23, 'Dave Builder', 'Labour', null, null, '2nd fix - 1st floor', null, null, null, null, 0, 0, 0, 'Planned', 2110.0, 2110.0, 0, 'diary'),
  (v_user, v_project, 1, 'Vince', 'Labour', null, null, '2 days', 'Vince', null, '2025-11-17'::date, null, 0, 0, 0, 'Paid', 440.0, 440.0, 440.0, 'ledger'),
  (v_user, v_project, 1, 'Venkat', 'Labour', null, null, '6 days', 'Venkat', null, '2025-11-17'::date, null, 0, 0, 0, 'Paid', 525.0, 525.0, 525.0, 'ledger'),
  (v_user, v_project, 1, 'Dave Gardener', 'Labour', null, null, null, 'Dave Gardener', null, '2025-11-17'::date, null, 0, 0, 0, 'Paid', 1350.0, 1350.0, 1350.0, 'ledger'),
  (v_user, v_project, 1, 'James Chippy', 'Labour', null, null, '2 days plus fixings', 'James Chippy', null, '2025-11-13'::date, null, 0, 0, 0, 'Paid', 510.0, 510.0, 510.0, 'ledger'),
  (v_user, v_project, 1, 'Vince', 'Labour', null, null, '5 days - £540 towards Mac', 'Vince', null, '2025-11-14'::date, null, 0, 0, 0, 'Paid', 1100.0, 1100.0, 1100.0, 'ledger'),
  (v_user, v_project, 1, 'Venkat', 'Labour', null, null, '5 days', 'Venkat', null, '2025-11-14'::date, null, 0, 0, 0, 'Paid', 375.0, 375.0, 375.0, 'ledger'),
  (v_user, v_project, 1, 'James Chippy', 'Labour', null, null, '1 day plus materials', 'James Chippy', null, '2025-11-20'::date, null, 0, 0, 0, 'Paid', 270.0, 270.0, 270.0, 'ledger'),
  (v_user, v_project, 1, 'Dave Gardener', 'Labour', null, null, '5 days labour', 'Dave Gardener', null, '2025-11-21'::date, null, 0, 0, 0, 'Paid', 2250.0, 2250.0, 2250.0, 'ledger'),
  (v_user, v_project, 1, 'Venky', 'Labour', null, null, '4 days Venky, 1 day AJ, Anil, Barat', 'Venky', null, '2025-11-21'::date, null, 0, 0, 0, 'Paid', 540.0, 540.0, 540.0, 'ledger'),
  (v_user, v_project, 1, 'Vince + Simon', 'Labour', null, null, '2 days for UFH + Chippy studs in bathrooms (£480 to mac)', 'Vince + Simon', null, '2025-11-21'::date, null, 0, 0, 0, 'Paid', 440.0, 440.0, 440.0, 'ledger'),
  (v_user, v_project, 1, 'Dave Gardener', 'Labour', null, null, '3 days to finish back garden inc slabbing all around 100m2', 'Dave Gardener', null, '2025-11-28'::date, null, 0, 0, 0, 'Paid', 1350.0, 1350.0, 1350.0, 'ledger'),
  (v_user, v_project, 1, 'Dave / Simon', 'Labour', null, null, '5 days - gutters / fascias entire week (! Day on fixing window area)', 'Dave / Simon', null, '2025-11-28'::date, null, 0, 0, 0, 'Paid', 1100.0, 1100.0, 1100.0, 'ledger'),
  (v_user, v_project, 1, 'Martin Plasterer', 'Labour', null, null, '2 days for 3 lads', 'Martin Plasterer', null, '2025-11-28'::date, null, 0, 0, 0, 'Paid', 1000.0, 1000.0, 1000.0, 'ledger'),
  (v_user, v_project, 1, 'Venky', 'Labour', null, null, '7 man days for labourers….. Turfing... Garden …. Then Thurs Frid helping simon with Fascias', 'Venky', null, '2025-11-28'::date, null, 0, 0, 0, 'Paid', 525.0, 525.0, 525.0, 'ledger'),
  (v_user, v_project, 1, 'Plasterers', 'Labour', null, null, '2 plasterers SAT 29/11', 'Plasterers', null, '2025-11-29'::date, null, 0, 0, 0, 'Paid', 400.0, 400.0, 400.0, 'ledger'),
  (v_user, v_project, 1, 'Venky', 'Labour', null, null, '2 days labour', 'Venky', null, '2025-12-05'::date, null, 0, 0, 0, 'Paid', 150.0, 150.0, 150.0, 'ledger'),
  (v_user, v_project, 1, 'Garden', 'Labour', null, null, 'clear 7 tree stumps out front', 'Garden', null, '2025-12-05'::date, null, 0, 0, 0, 'Paid', 300.0, 300.0, 300.0, 'ledger'),
  (v_user, v_project, 1, 'Roof clean plus repair', 'Labour', null, null, null, 'Roof clean plus repair', null, '2025-12-05'::date, null, 0, 0, 0, 'Paid', 1300.0, 1300.0, 1300.0, 'ledger'),
  (v_user, v_project, 1, 'dave', 'Labour', null, null, '2 days simon plus materials', 'dave', null, '2025-12-05'::date, null, 0, 0, 0, 'Paid', 460.0, 460.0, 460.0, 'ledger'),
  (v_user, v_project, 1, 'Tiler', 'Labour', null, null, 'Tiler paid - £2500 remaining', 'Tiler', null, '2025-12-05'::date, null, 0, 0, 0, 'Paid', 1500.0, 1500.0, 1500.0, 'ledger'),
  (v_user, v_project, 1, 'SRI Kitchen fitters', 'Labour', null, null, 'Cash paid', 'SRI Kitchen fitters', null, '2025-12-12'::date, null, 0, 0, 0, 'Paid', 1600.0, 1600.0, 1600.0, 'ledger'),
  (v_user, v_project, 1, 'Tiler', 'Labour', null, null, null, 'Tiler', null, '2025-12-12'::date, null, 0, 0, 0, 'Paid', 1000.0, 1000.0, 1000.0, 'ledger'),
  (v_user, v_project, 1, 'Stuart Miscoat', 'Labour', null, null, 'Spray miscoat', 'Stuart Miscoat', null, '2025-12-12'::date, null, 0, 0, 0, 'Paid', 150.0, 150.0, 150.0, 'ledger'),
  (v_user, v_project, 1, 'Dave / Simon', 'Labour', null, null, 'Paid… £1050….  £50 towards Mac', 'Dave / Simon', null, '2025-12-12'::date, null, 0, 0, 0, 'Paid', 1100.0, 1100.0, 1100.0, 'ledger'),
  (v_user, v_project, 1, 'Dave Gardener', 'Labour', null, null, '1/2 day …. Dave and co slabbed the front…. 15m2 layed', 'Dave Gardener', null, '2025-12-12'::date, null, 0, 0, 0, 'Paid', 225.0, 225.0, 225.0, 'ledger'),
  (v_user, v_project, 1, 'Mickey - Grout Garden', 'Labour', null, null, null, 'Mickey - Grout Garden', null, '2025-12-13'::date, null, 0, 0, 0, 'Paid', 150.0, 150.0, 150.0, 'ledger'),
  (v_user, v_project, 1, 'Tom Chippie', 'Labour', null, null, 'Paid… £30 per hour Tom + £25 / hour for his mate', 'Tom Chippie', null, '2025-11-14'::date, null, 0, 0, 0, 'Paid', 565.0, 565.0, 565.0, 'ledger'),
  (v_user, v_project, 1, 'Venky', 'Labour', null, null, '2.5 days.', 'Venky', null, '2025-12-15'::date, null, 0, 0, 0, 'Paid', 150.0, 150.0, 150.0, 'ledger'),
  (v_user, v_project, 1, 'Dave Gardener', 'Labour', null, null, '1 day dave… finished job', 'Dave Gardener', null, '2025-12-15'::date, null, 0, 0, 0, 'Paid', 300.0, 300.0, 300.0, 'ledger'),
  (v_user, v_project, 1, 'Dan Painter', 'Labour', null, null, '3 days Stu @ £160 + 1 day Dan @ £170', 'Dan Painter', null, '2025-12-19'::date, null, 0, 0, 0, 'Paid', 650.0, 650.0, 650.0, 'ledger'),
  (v_user, v_project, 1, 'Tiler', 'Labour', null, null, 'remaining tile labour - £200 for extra adhesive', 'Tiler', null, '2025-12-19'::date, null, 0, 0, 0, 'Paid', 1610.0, 1610.0, 1610.0, 'ledger'),
  (v_user, v_project, 1, 'Dan Painter', 'Labour', null, null, 'bank transfer', 'Dan Painter', null, '2025-12-23'::date, null, 0, 0, 0, 'Paid', 550.0, 550.0, 550.0, 'ledger'),
  (v_user, v_project, 1, 'Dave Chippie', 'Labour', null, null, 'Chippie for bespoke cupboard in utility', 'Dave Chippie', null, '2026-01-09'::date, null, 0, 0, 0, 'Paid', 220.0, 220.0, 220.0, 'ledger'),
  (v_user, v_project, 1, 'Dan Painter', 'Labour', null, null, null, 'Dan Painter', null, '2026-01-09'::date, null, 0, 0, 0, 'Paid', 1075.0, 1075.0, 1075.0, 'ledger'),
  (v_user, v_project, 1, 'Dan Painter', 'Labour', null, null, null, 'Dan Painter', null, '2026-01-16'::date, null, 0, 0, 0, 'Paid', 100.0, 100.0, 100.0, 'ledger'),
  (v_user, v_project, 1, 'Venkat', 'Labour', null, null, 'final clean up, soffit paints etc', 'Venkat', null, '2026-01-16'::date, null, 0, 0, 0, 'Paid', 100.0, 100.0, 100.0, 'ledger'),
  (v_user, v_project, 1, 'Alspec Windows', 'Materials', null, null, 'Bank T Walkern', 'Alspec Windows', null, '2025-11-02'::date, 'Bank Transfer', 1.0, 5000.0, 0, 'Paid', 5000.0, 5000.0, 5000.0, 'ledger'),
  (v_user, v_project, 1, 'Stevenage Skips', 'Materials', null, null, 'Cash payment', 'Stevenage Skips', null, '2025-11-04'::date, 'Cash', 1.0, 390.0, 0, 'Paid', 390.0, 390.0, 390.0, 'ledger'),
  (v_user, v_project, 1, 'Wunda UFH', 'Materials', null, null, 'Bank T Walkern - Deposit paid 90% remaining', 'Wunda UFH', null, '2025-11-03'::date, 'Bank Transfer', 1.0, 416.05, 0, 'Paid', 416.05, 416.05, 416.05, 'ledger'),
  (v_user, v_project, 1, 'Wunda UFH', 'Materials', null, null, 'Wunda UFH - Bank T', 'Wunda UFH', null, '2025-11-05'::date, 'Bank Transfer', 1.0, 3586.0, 0, 'Paid', 3586.0, 3586.0, 3586.0, 'ledger'),
  (v_user, v_project, 1, 'Kitchen- Cabinets Direct', 'Materials', null, null, 'Paid Cash - £2500 remaining', 'Kitchen- Cabinets Direct', null, '2025-11-07'::date, 'Cash', 1.0, 6000.0, 0, 'Paid', 6000.0, 6000.0, 6000.0, 'ledger'),
  (v_user, v_project, 1, 'Lawsons', 'Materials', null, null, 'Paid Mama', 'Lawsons', null, '2025-11-10'::date, null, 1.0, 336.78, 0, 'Paid', 336.78, 336.78, 336.78, 'ledger'),
  (v_user, v_project, 1, 'Lawsons', 'Materials', null, null, 'Paid Mama', 'Lawsons', null, '2025-11-10'::date, null, 1.0, 252.0, 0, 'Paid', 252.0, 252.0, 252.0, 'ledger'),
  (v_user, v_project, 1, 'Tree Clearence - Garden', 'Materials', null, null, 'Paid Cash', 'Tree Clearence - Garden', null, '2025-11-12'::date, 'Cash', 1.0, 320.0, 0, 'Paid', 320.0, 320.0, 320.0, 'ledger'),
  (v_user, v_project, 1, 'Electrics', 'Materials', null, null, 'Paid Cash', 'Electrics', null, '2025-11-14'::date, 'Cash', 1.0, 4000.0, 0, 'Paid', 4000.0, 4000.0, 4000.0, 'ledger'),
  (v_user, v_project, 1, 'Plumbing', 'Materials', null, null, 'Paid Cash', 'Plumbing', null, '2025-11-15'::date, 'Cash', 1.0, 1000.0, 0, 'Paid', 1000.0, 1000.0, 1000.0, 'ledger'),
  (v_user, v_project, 1, 'Lawsons - Garden £500', 'Materials', null, null, 'Paid Mama', 'Lawsons - Garden £500', null, '2025-11-14'::date, null, 1.0, 655.72, 0, 'Paid', 655.72, 655.72, 655.72, 'ledger'),
  (v_user, v_project, 1, 'Distribution Tiles - GARDEN', 'Materials', null, null, 'Paid Mama', 'Distribution Tiles - GARDEN', null, '2025-11-14'::date, null, 1.0, 1829.16, 0, 'Paid', 1829.16, 1829.16, 1829.16, 'ledger'),
  (v_user, v_project, 1, 'Alpec Windows', 'Materials', null, null, 'Paid Cash', 'Alpec Windows', null, '2025-11-14'::date, 'Cash', 1.0, 1000.0, 0, 'Paid', 1000.0, 1000.0, 1000.0, 'ledger'),
  (v_user, v_project, 1, 'Plumbing', 'Materials', null, null, 'Paid cash', 'Plumbing', null, '2025-11-22'::date, 'Cash', 1.0, 1000.0, 0, 'Paid', 1000.0, 1000.0, 1000.0, 'ledger'),
  (v_user, v_project, 1, 'Pro Tiler', 'Materials', null, null, 'Paid AMEX - Prima + ditra + Adhesive', 'Pro Tiler', null, '2025-11-20'::date, null, 1.0, 1164.14, 0, 'Paid', 1164.14, 1164.14, 1164.14, 'ledger'),
  (v_user, v_project, 1, 'Sam- Hedge removal + clear - Garden', 'Materials', null, null, 'paid cash', 'Sam- Hedge removal + clear - Garden', null, '2025-11-19'::date, 'Cash', 1.0, 200.0, 0, 'Paid', 200.0, 200.0, 200.0, 'ledger'),
  (v_user, v_project, 1, 'Lusso Stone', 'Materials', null, null, 'Paid dad debit card', 'Lusso Stone', null, '2025-11-20'::date, 'Debit Card', 1.0, 1456.0, 0, 'Paid', 1456.0, 1456.0, 1456.0, 'ledger'),
  (v_user, v_project, 1, 'Eurocell', 'Materials', null, null, 'Paid cash', 'Eurocell', null, '2025-11-21'::date, 'Cash', 1.0, 650.0, 0, 'Paid', 650.0, 650.0, 650.0, 'ledger'),
  (v_user, v_project, 1, 'Lawsons', 'Materials', null, null, 'paid cap on tap watton card', 'Lawsons', null, '2025-11-21'::date, null, 1.0, 205.38, 0, 'Paid', 205.38, 205.38, 205.38, 'ledger'),
  (v_user, v_project, 1, 'Hauws Gray - Garden', 'Materials', null, null, 'Paid cash for bullnose garden etc', 'Hauws Gray - Garden', null, '2025-11-21'::date, 'Cash', 1.0, 500.0, 0, 'Paid', 500.0, 500.0, 500.0, 'ledger'),
  (v_user, v_project, 1, 'Distribution Tiles', 'Materials', null, null, 'Paid via shop', 'Distribution Tiles', null, '2025-11-21'::date, null, 1.0, 2221.98, 0, 'Paid', 2221.98, 2221.98, 2221.98, 'ledger'),
  (v_user, v_project, 1, 'Rest of bathroom - Various', 'Materials', null, null, 'Paid dad debit card', 'Rest of bathroom - Various', null, '2025-11-23'::date, 'Debit Card', 1.0, 3100.0, 0, 'Paid', 3100.0, 3100.0, 3100.0, 'ledger'),
  (v_user, v_project, 1, 'Lawsons', 'Materials', null, null, 'paid mama', 'Lawsons', null, '2025-11-24'::date, null, 1.0, 189.0, 0, 'Paid', 189.0, 189.0, 189.0, 'ledger'),
  (v_user, v_project, 1, 'George Davies Turf - Garden', 'Materials', null, null, 'Paid dad debit card', 'George Davies Turf - Garden', null, '2025-11-25'::date, 'Debit Card', 1.0, 586.2, 0, 'Paid', 586.2, 586.2, 586.2, 'ledger'),
  (v_user, v_project, 1, 'Tool Station', 'Materials', null, null, 'Cap on tap', 'Tool Station', null, '2025-11-26'::date, null, 1.0, 31.98, 0, 'Paid', 31.98, 31.98, 31.98, 'ledger'),
  (v_user, v_project, 1, 'Build BASE - Garden', 'Materials', null, null, 'Cap on tap', 'Build BASE - Garden', null, '2025-11-26'::date, null, 1.0, 132.0, 0, 'Paid', 132.0, 132.0, 132.0, 'ledger'),
  (v_user, v_project, 1, 'Pro Tiler', 'Materials', null, null, 'dad debit card', 'Pro Tiler', null, '2025-11-26'::date, 'Debit Card', 1.0, 1272.41, 0, 'Paid', 1272.41, 1272.41, 1272.41, 'ledger'),
  (v_user, v_project, 1, 'Clearence guys', 'Materials', null, null, 'Cash payment', 'Clearence guys', null, '2025-11-28'::date, 'Cash', 1.0, 650.0, 0, 'Paid', 650.0, 650.0, 650.0, 'ledger'),
  (v_user, v_project, 1, 'Plumbing', 'Materials', null, null, 'Cash payment', 'Plumbing', null, '2025-11-28'::date, 'Cash', 1.0, 3000.0, 0, 'Paid', 3000.0, 3000.0, 3000.0, 'ledger'),
  (v_user, v_project, 1, 'Eurocell', 'Materials', null, null, 'Cap on tap', 'Eurocell', null, '2025-11-28'::date, null, 1.0, 50.0, 0, 'Paid', 50.0, 50.0, 50.0, 'ledger'),
  (v_user, v_project, 1, 'welwyn skips', 'Materials', null, null, 'dad debit card', 'welwyn skips', null, '2025-12-01'::date, 'Debit Card', 1.0, 426.0, 0, 'Paid', 426.0, 426.0, 426.0, 'ledger'),
  (v_user, v_project, 1, 'Howdens', 'Materials', null, null, 'on account', 'Howdens', null, '2025-12-01'::date, null, 1.0, 1917.0, 0, 'Paid', 1917.0, 1917.0, 1917.0, 'ledger'),
  (v_user, v_project, 1, 'Lawsons', 'Materials', null, null, 'mama', 'Lawsons', null, '2025-12-02'::date, null, 1.0, 290.84, 0, 'Paid', 290.84, 290.84, 290.84, 'ledger'),
  (v_user, v_project, 1, 'Tops tiles', 'Materials', null, null, 'Cap on tap', 'Tops tiles', null, '2025-12-03'::date, null, 1.0, 131.16, 0, 'Paid', 131.16, 131.16, 131.16, 'ledger'),
  (v_user, v_project, 1, 'gills plumbing', 'Materials', null, null, 'sanj card', 'gills plumbing', null, '2025-12-05'::date, null, 1.0, 250.0, 0, 'Paid', 250.0, 250.0, 250.0, 'ledger'),
  (v_user, v_project, 1, 'Kitchen- Cabinets Direct', 'Materials', null, null, 'Cash payment', 'Kitchen- Cabinets Direct', null, '2025-12-05'::date, 'Cash', 1.0, 2000.0, 0, 'Paid', 2000.0, 2000.0, 2000.0, 'ledger'),
  (v_user, v_project, 1, 'Johnstones Paint', 'Materials', null, null, 'dad card', 'Johnstones Paint', null, '2025-12-08'::date, null, 1.0, 70.0, 0, 'Paid', 70.0, 70.0, 70.0, 'ledger'),
  (v_user, v_project, 1, 'AC Tools', 'Materials', null, null, 'Cash payment', 'AC Tools', null, '2025-12-09'::date, 'Cash', 1.0, 70.0, 0, 'Paid', 70.0, 70.0, 70.0, 'ledger'),
  (v_user, v_project, 1, 'George Davies Turf - Garden', 'Materials', null, null, 'dad debit card', 'George Davies Turf - Garden', null, '2025-12-12'::date, 'Debit Card', 1.0, 424.32, 0, 'Paid', 424.32, 424.32, 424.32, 'ledger'),
  (v_user, v_project, 1, 'Skips', 'Materials', null, null, 'dad debit card', 'Skips', null, '2025-12-12'::date, 'Debit Card', 1.0, 490.0, 0, 'Paid', 490.0, 490.0, 490.0, 'ledger'),
  (v_user, v_project, 1, 'Tiles - Trims etc', 'Materials', null, null, 'Cash payment', 'Tiles - Trims etc', null, '2025-12-12'::date, 'Cash', 1.0, 460.0, 0, 'Paid', 460.0, 460.0, 460.0, 'ledger'),
  (v_user, v_project, 1, 'Plumbing', 'Materials', null, null, 'Cash payment', 'Plumbing', null, '2025-12-12'::date, 'Cash', 1.0, 1000.0, 0, 'Paid', 1000.0, 1000.0, 1000.0, 'ledger'),
  (v_user, v_project, 1, 'Alspec Windows', 'Materials', null, null, 'Paid via invoices to shops', 'Alspec Windows', null, '2025-12-01'::date, null, 1.0, 2500.0, 0, 'Paid', 2500.0, 2500.0, 2500.0, 'ledger'),
  (v_user, v_project, 1, 'Distribution Tiles', 'Materials', null, null, 'Paid dad debit card', 'Distribution Tiles', null, '2025-12-15'::date, 'Debit Card', 1.0, 175.0, 0, 'Paid', 175.0, 175.0, 175.0, 'ledger'),
  (v_user, v_project, 1, 'Appliances Kitchen', 'Materials', null, null, 'Paid dad debit card', 'Appliances Kitchen', null, '2025-12-16'::date, 'Debit Card', 1.0, 2958.0, 0, 'Paid', 2958.0, 2958.0, 2958.0, 'ledger'),
  (v_user, v_project, 1, 'Johnstones Paint', 'Materials', null, null, 'Paid dad debit card', 'Johnstones Paint', null, '2025-12-16'::date, 'Debit Card', 1.0, 379.0, 0, 'Paid', 379.0, 379.0, 379.0, 'ledger'),
  (v_user, v_project, 1, 'Cawdor', 'Materials', null, null, 'Cash payment', 'Cawdor', null, '2025-12-17'::date, 'Cash', 1.0, 3450.0, 0, 'Paid', 3450.0, 3450.0, 3450.0, 'ledger'),
  (v_user, v_project, 1, 'Kitchen- Cabinets Direct', 'Materials', null, null, 'Cash payment', 'Kitchen- Cabinets Direct', null, '2025-12-17'::date, 'Cash', 1.0, 900.0, 0, 'Paid', 900.0, 900.0, 900.0, 'ledger'),
  (v_user, v_project, 1, 'Electrics', 'Materials', null, null, 'Cash payment', 'Electrics', null, '2025-12-22'::date, 'Cash', 1.0, 5130.0, 0, 'Paid', 5130.0, 5130.0, 5130.0, 'ledger'),
  (v_user, v_project, 1, 'Johnstones Paint', 'Materials', null, null, 'debit card dad', 'Johnstones Paint', null, '2025-12-22'::date, 'Debit Card', 1.0, 276.0, 0, 'Paid', 276.0, 276.0, 276.0, 'ledger'),
  (v_user, v_project, 1, 'Plumbing', 'Materials', null, null, 'Cash payment', 'Plumbing', null, '2025-12-24'::date, 'Cash', 1.0, 1500.0, 0, 'Paid', 1500.0, 1500.0, 1500.0, 'ledger'),
  (v_user, v_project, 1, 'Misc cupboard materials', 'Materials', null, null, 'Cash payment', 'Misc cupboard materials', null, '2026-01-09'::date, 'Cash', 1.0, 145.0, 0, 'Paid', 145.0, 145.0, 145.0, 'ledger'),
  (v_user, v_project, 1, 'Plumbing', 'Materials', null, null, 'Cash payment', 'Plumbing', null, '2026-01-09'::date, 'Cash', 1.0, 500.0, 0, 'Paid', 500.0, 500.0, 500.0, 'ledger'),
  (v_user, v_project, 1, 'Alspec Windows', 'Materials', null, null, 'Cash payment', 'Alspec Windows', null, '2026-01-09'::date, 'Cash', 1.0, 1000.0, 0, 'Paid', 1000.0, 1000.0, 1000.0, 'ledger'),
  (v_user, v_project, 1, 'Carpets', 'Materials', null, null, 'Cash payment', 'Carpets', null, '2026-01-09'::date, 'Cash', 1.0, 900.0, 0, 'Paid', 900.0, 900.0, 900.0, 'ledger'),
  (v_user, v_project, 1, 'Alspec Windows', 'Materials', null, null, 'to be paid', 'Alspec Windows', null, '2026-01-25'::date, null, 1.0, 1500.0, 0, 'Paid', 1500.0, 1500.0, 1500.0, 'ledger'),
  (v_user, v_project, 1, 'Staging', 'Materials', null, null, 'paid', 'Staging', null, '2026-01-14'::date, null, 1.0, 2225.0, 0, 'Paid', 2225.0, 2225.0, 2225.0, 'ledger'),
  (v_user, v_project, 1, 'Driveway Clean + front garden cleared', 'Materials', null, null, 'Kevin', 'Driveway Clean + front garden cleared', null, '2026-01-14'::date, null, 1.0, 140.0, 0, 'Paid', 140.0, 140.0, 140.0, 'ledger'),
  (v_user, v_project, 1, 'Mastic Man', 'Materials', null, null, 'Cash payment', 'Mastic Man', null, '2026-01-16'::date, 'Cash', 1.0, 100.0, 0, 'Paid', 100.0, 100.0, 100.0, 'ledger'),
  (v_user, v_project, 1, 'Plumbing', 'Materials', null, null, 'Cash payment', 'Plumbing', null, '2026-01-24'::date, 'Cash', 1.0, 1000.0, 0, 'Paid', 1000.0, 1000.0, 1000.0, 'ledger');

  insert into public.trade_lookups (user_id, name, default_rate, default_markup_pct) values
  (v_user, 'General Builder', 45.0, 10.0),
  (v_user, 'Carpenter/Joiner', 50.0, 10.0),
  (v_user, 'Plumber', 60.0, 10.0),
  (v_user, 'Electrician', 65.0, 10.0),
  (v_user, 'Plasterer', 55.0, 10.0),
  (v_user, 'Tiler', 55.0, 10.0),
  (v_user, 'Decorator', 45.0, 10.0),
  (v_user, 'Roofer', 60.0, 10.0),
  (v_user, 'Groundworker', 55.0, 10.0),
  (v_user, 'Kitchen Fitter', 55.0, 10.0),
  (v_user, 'Bathroom Fitter', 55.0, 10.0),
  (v_user, 'Glazier', 55.0, 10.0),
  (v_user, 'Scaffolder', 55.0, 10.0),
  (v_user, 'Flooring Installer', 50.0, 10.0),
  (v_user, 'Skip/Disposal', 0.0, 0.0),
  (v_user, 'Other', 50.0, 10.0)
  on conflict (user_id, name) do update
    set default_rate = excluded.default_rate,
        default_markup_pct = excluded.default_markup_pct;

  insert into public.project_weeks (user_id, project_id, week_number, completion_pct)
  select v_user, v_project, generate_series(1, 23), 0
  on conflict (project_id, week_number) do nothing;

  raise notice 'Imported project % (111 diary + 96 ledger rows).', v_project;
end $$;

-- ------------------------------------------------------------------
-- Self-check: every week's diary total must equal the spreadsheet's
-- 'Summary' -> 'By Week (Totals)' figure. Any disagreement aborts the
-- transaction, so a bad import can never be committed by accident.
-- ------------------------------------------------------------------
do $$
declare
  v_user  uuid := '5d3fc9ff-92a3-4923-a18b-7eb5eade3105';
  r       record;
  v_bad   int := 0;
begin
  for r in
    with expected(week_number, sheet_total) as (values
      (1, 1770.0::numeric),
      (2, 1675.0::numeric),
      (3, 525.0::numeric),
      (4, 1550.0::numeric),
      (5, 3205.0::numeric),
      (6, 2500.0::numeric),
      (7, 2048.4::numeric),
      (8, 2425.0::numeric),
      (9, 6110.0::numeric),
      (10, 2915.0::numeric),
      (11, 700.0::numeric),
      (12, 4000.0::numeric),
      (13, 2575.0::numeric),
      (14, 2520.0::numeric),
      (15, 7893.41::numeric),
      (16, 18418.28::numeric),
      (17, 16287.68::numeric),
      (18, 12686.23::numeric),
      (19, 10018.96::numeric),
      (20, 4930.75::numeric),
      (21, 5388.79::numeric),
      (22, 18571.82::numeric),
      (23, 22930.45::numeric)
    ),
    got as (
      select e.week_number,
             sum(e.actual_amount * (1 + e.vat_rate / 100)) as app_total
      from public.expense_entries e
      join public.projects p on p.id = e.project_id
      where p.user_id = v_user
        and p.name   = '46 Glenferrie Road'
        and e.source = 'diary'
        and e.status <> 'Cancelled'
      group by e.week_number
    )
    select expected.week_number, expected.sheet_total,
           coalesce(got.app_total, 0) as app_total
    from expected left join got using (week_number)
    order by expected.week_number
  loop
    if abs(r.app_total - r.sheet_total) > 0.01 then
      v_bad := v_bad + 1;
      raise warning 'Week %: app % <> spreadsheet %',
        r.week_number, round(r.app_total, 2), r.sheet_total;
    end if;
  end loop;

  if v_bad > 0 then
    raise exception '% week(s) do not match the spreadsheet — nothing committed.', v_bad;
  end if;
  raise notice 'All 23 weeks match the spreadsheet.';
end $$;

commit;
-- rollback;  -- use instead of commit if the numbers look wrong

-- ------------------------------------------------------------------
-- Report. Compare these against the spreadsheet's Summary tab.
-- ------------------------------------------------------------------
select 'Total Quoted'      as card, sum(quoted_amount)                          as value
from public.expense_entries e join public.projects p on p.id = e.project_id
where p.user_id = '5d3fc9ff-92a3-4923-a18b-7eb5eade3105' and p.name = '46 Glenferrie Road'
  and e.source = 'diary' and e.status <> 'Cancelled'
union all
select 'Actual Total (incl. VAT)', sum(actual_amount * (1 + vat_rate / 100))
from public.expense_entries e join public.projects p on p.id = e.project_id
where p.user_id = '5d3fc9ff-92a3-4923-a18b-7eb5eade3105' and p.name = '46 Glenferrie Road'
  and e.source = 'diary' and e.status <> 'Cancelled'
union all
select 'Paid to Date', sum(paid_amount)
from public.expense_entries e join public.projects p on p.id = e.project_id
where p.user_id = '5d3fc9ff-92a3-4923-a18b-7eb5eade3105' and p.name = '46 Glenferrie Road'
  and e.source = 'diary' and e.status <> 'Cancelled'
union all
select 'Weeks Tracked', count(distinct week_number)
from public.expense_entries e join public.projects p on p.id = e.project_id
where p.user_id = '5d3fc9ff-92a3-4923-a18b-7eb5eade3105' and p.name = '46 Glenferrie Road'
  and e.source = 'diary' and e.status <> 'Cancelled'
union all
select 'Diary rows', count(*)
from public.expense_entries e join public.projects p on p.id = e.project_id
where p.user_id = '5d3fc9ff-92a3-4923-a18b-7eb5eade3105' and p.name = '46 Glenferrie Road' and e.source = 'diary'
union all
select 'Ledger rows', count(*)
from public.expense_entries e join public.projects p on p.id = e.project_id
where p.user_id = '5d3fc9ff-92a3-4923-a18b-7eb5eade3105' and p.name = '46 Glenferrie Road' and e.source = 'ledger';
