-- RenovaTrack — rebuild from the Week-by-Week Plan alone, weeks 1-23.
-- GENERATED by scripts/build_import_sql.py — do not hand-edit.
--
-- Owner  : 5d3fc9ff-92a3-4923-a18b-7eb5eade3105 (admin@pk.com)
-- Diary  : 111 rows, weeks 1-23
--          (46_Glenferrie_Rd_Renovation_Spend_Tracker_Updated.xlsx,
--           'Week-by-Week Plan')
-- Trades : 16 lookups (same file, 'Lookups')
-- Supplrs: 33 merchants on 46 rows. The sheet's
--          'Supplier' column is NOT the source: it has 8 non-empty cells
--          and 7 are notes typed into the wrong column ('steels in',
--          '£300 PAID FROM OWED'). The merchant names were typed into
--          'Task / Description' on the Materials rows, and that is where
--          this import reads them from, against a list confirmed by the
--          owner (SUPPLIER_NAMES in the script). The 7 notes are moved
--          into notes, where they belong. Re-run 0008 afterwards to
--          reseed public.suppliers and link every purchase to one.
-- Ledger : 0 rows — Renovation_Cost_Tracker-1.xlsx is NO LONGER
--          imported. It is a different job: it names no address, its
--          dates (2025-11-02 to 2026-01-25) stop a month before this
--          project's week 1, and it ends with carpets and staging while
--          week 1 here is 'clearance / back to brick'. It also broke the
--          Price Tracker — its Unit Cost column holds the amount of each
--          instalment, so a 416.05 deposit followed by a 3,586.00 balance
--          to Wunda UFH read as a 761.9% price rise. The workbook stays
--          in the repo; it is simply not imported.
--
-- Supersedes 0005, 0006 and 0007. Do NOT run any of those again.
--
-- target_budget is set to 0 because the spreadsheet's own 'Target Budget
-- (incl. VAT)' cell is blank. The budget card and the '% of budget' bar
-- hide themselves at 0 rather than comparing spend against another job's
-- total, which is what the old 98,932.12 figure was.
--
-- Money mapping — actual_amount is EX-VAT because the app derives
--   total_incl_vat = actual_amount x (1 + vat_rate/100)
-- on every read (lib/calculations.ts). Storing an incl-VAT figure here
-- is what made the old import show VAT twice.
--   actual_amount = Labour Cost + Materials Cost   (ex-VAT)
--   quoted_amount = Total incl. VAT                (the sheet's forecast)
--   paid_amount   = Total incl. VAT, when a Paid Date is filled
--
-- After this runs the Overview tab should read:
--   Total Quoted      £151,644.78
--   Actual Total      £151,644.78   (= the sheet's Forecast Total)
--   Variance vs Quote £-0.00
--   Paid to Date      £13,273.40   (= the sheet's 'Paid to date')
--   Remaining to Pay  £138,371.38  (= the sheet's 'Committed')
--   Weeks Tracked     23
--
-- Run in the Supabase SQL editor. Re-runnable: it deletes this user's
-- existing copy of the project first. It refuses to commit if any week
-- total disagrees with the spreadsheet.

begin;

do $$
declare
  v_user    uuid := '5d3fc9ff-92a3-4923-a18b-7eb5eade3105';
  v_project uuid;
begin
  if not exists (select 1 from auth.users where id = v_user) then
    raise exception 'User % not found in auth.users.', v_user;
  end if;

  -- Idempotency: clear any prior import of this project. Cascades to
  -- expense_entries, project_weeks, and (from 0008) purchases with their
  -- lines, payments and receipt rows.
  delete from public.projects where user_id = v_user and name = '46 Glenferrie Road';

  -- 0008's suppliers and items sit ABOVE the project, so the delete above
  -- does not reach them: without this, every merchant seeded from the old
  -- File 2 import would linger on /suppliers and /items with no purchase
  -- behind it. Aliases cascade; purchases.supplier_id and
  -- purchase_lines.item_id are 'on delete set null', so nothing else
  -- breaks. Re-run 0008 afterwards to reseed them from what is left.
  delete from public.items     where user_id = v_user;
  delete from public.suppliers where user_id = v_user;

  insert into public.projects (user_id, name, target_budget, status, notes)
  values (v_user, '46 Glenferrie Road', 0.0, 'active',
          'Imported from the Week-by-Week Plan, weeks 1-23.')
  returning id into v_project;

  insert into public.expense_entries (user_id, project_id, week_number, description, category, trade, location_room, notes, supplier, invoice_ref, paid_date, payment_method, qty, unit_cost, vat_rate, status, quoted_amount, actual_amount, paid_amount, source) values
  (v_user, v_project, 1, 'Labourers', 'Labour', 'General Builder', null, 'Clearence - 6 man days | Rate: 45.0', null, null, '2026-02-27'::date, 'Cash', 0, 0, 0, 'Paid', 450.0, 450.0, 450.0, 'diary'),
  (v_user, v_project, 1, 'DMC - Dave', 'Labour', 'General Builder', null, 'Dave first day on site | Rate: 45.0', null, null, '2026-02-27'::date, 'Cash', 0, 0, 0, 'Paid', 220.0, 220.0, 220.0, 'diary'),
  (v_user, v_project, 1, 'Adam - Clearance', 'Labour', 'Skip/Disposal', null, 'Rubbish Removal', null, null, '2026-02-27'::date, 'Cash', 0, 0, 0, 'Paid', 1100.0, 1100.0, 1100.0, 'diary'),
  (v_user, v_project, 2, 'Labourers', 'Labour', 'General Builder', null, 'Clearence / back to brick - 9 d | Rate: 45.0', null, null, '2026-03-06'::date, 'Cash', 0, 0, 0, 'Paid', 675.0, 675.0, 675.0, 'diary'),
  (v_user, v_project, 2, 'Adam - Clearance', 'Labour', 'Skip/Disposal', null, 'Rubbish Removal', null, null, '2026-03-06'::date, 'Cash', 0, 0, 0, 'Paid', 1000.0, 1000.0, 1000.0, 'diary'),
  (v_user, v_project, 3, 'Labourers', 'Labour', 'General Builder', null, 'Clearence / back to brick - 7 d | Rate: 45.0', null, null, '2026-03-13'::date, 'Cash', 0, 0, 0, 'Paid', 525.0, 525.0, 525.0, 'diary'),
  (v_user, v_project, 4, 'Labourers', 'Labour', 'General Builder', null, 'Clearance 6d | Rate: 45.0', null, null, '2026-03-20'::date, 'Cash', 0, 0, 0, 'Paid', 450.0, 450.0, 450.0, 'diary'),
  (v_user, v_project, 4, 'Adam - Clearance', 'Labour', 'Skip/Disposal', null, null, null, null, '2026-03-20'::date, 'Cash', 0, 0, 0, 'Paid', 1100.0, 1100.0, 1100.0, 'diary'),
  (v_user, v_project, 5, 'Skip', 'Labour', 'Skip/Disposal', null, null, 'Stevenage Skips', null, '2026-03-27'::date, 'Cash', 0, 0, 0, 'Paid', 480.0, 480.0, 480.0, 'diary'),
  (v_user, v_project, 5, 'Labourers', 'Labour', 'General Builder', null, 'Rate: 45.0', null, null, '2026-03-27'::date, 'Cash', 0, 0, 0, 'Paid', 450.0, 450.0, 450.0, 'diary'),
  (v_user, v_project, 5, 'Dave Barker (Groundwork)', 'Labour', 'General Builder', null, 'Rate: 45.0', null, null, '2026-03-27'::date, 'Cash', 0, 0, 0, 'Paid', 1250.0, 1250.0, 1250.0, 'diary'),
  (v_user, v_project, 5, 'Master Mix', 'Materials', 'Other', null, 'Rate: 50.0', 'Master Mix', null, '2026-03-27'::date, 'Debit Card', 0, 0, 0, 'Paid', 1025.0, 1025.0, 1025.0, 'diary'),
  (v_user, v_project, 6, 'Labourers', 'Labour', 'General Builder', null, 'Rate: 45.0', null, null, '2026-04-03'::date, 'Cash', 0, 0, 0, 'Paid', 300.0, 300.0, 300.0, 'diary'),
  (v_user, v_project, 6, 'Dave Barker (Groundwork)', 'Labour', 'General Builder', null, 'Rate: 45.0', null, null, '2026-04-03'::date, 'Cash', 0, 0, 0, 'Paid', 900.0, 900.0, 900.0, 'diary'),
  (v_user, v_project, 6, 'Dave Builder', 'Labour', 'General Builder', null, 'Rate: 45.0', null, null, '2026-04-03'::date, 'Cash', 0, 0, 0, 'Paid', 300.0, 300.0, 300.0, 'diary'),
  (v_user, v_project, 6, 'Steels', 'Materials', 'General Builder', null, 'Rate: 45.0', 'Steels', null, '2026-04-03'::date, 'Cash', 0, 0, 0, 'Paid', 1000.0, 1000.0, 1000.0, 'diary'),
  (v_user, v_project, 7, 'SDE Drainage', 'Materials', 'General Builder', null, 'Rate: 45.0', 'SDE Drainage', null, '2026-04-10'::date, 'Credit Card', 0, 0, 20, 'Paid', 98.4, 82.0, 98.4, 'diary'),
  (v_user, v_project, 7, 'Master Mix', 'Materials', 'General Builder', null, 'Rate: 45.0', 'Master Mix', null, '2026-04-10'::date, 'Debit Card', 0, 0, 20, 'Paid', 900.0, 750.0, 900.0, 'diary'),
  (v_user, v_project, 7, 'Labourers', 'Labour', 'General Builder', null, 'Rate: 45.0', null, null, '2026-04-10'::date, 'Cash', 0, 0, 0, 'Paid', 450.0, 450.0, 450.0, 'diary'),
  (v_user, v_project, 7, 'Dave', 'Labour', 'General Builder', null, '£300 PAID FROM OWED | Rate: 45.0', null, null, '2026-04-10'::date, 'Cash', 0, 0, 0, 'Paid', 600.0, 600.0, 600.0, 'diary'),
  (v_user, v_project, 8, 'dave', 'Labour', 'General Builder', null, '£400 paid from whats owed | Rate: 45.0', null, null, null, null, 0, 0, 0, 'Planned', 1400.0, 1400.0, 0, 'diary'),
  (v_user, v_project, 8, 'Labourers', 'Labour', 'General Builder', null, 'Rate: 45.0', null, null, null, null, 0, 0, 0, 'Planned', 750.0, 750.0, 0, 'diary'),
  (v_user, v_project, 8, 'Owen Brickwork', 'Labour', 'General Builder', null, '1 day - to DPC | Rate: 45.0', null, null, null, null, 0, 0, 0, 'Planned', 275.0, 275.0, 0, 'diary'),
  (v_user, v_project, 9, 'Owen Brickwork', 'Labour', 'General Builder', null, 'all brickwork completed | Rate: 45.0', null, null, null, null, 0, 0, 0, 'Planned', 1935.0, 1935.0, 0, 'diary'),
  (v_user, v_project, 9, 'Dave Builder', 'Labour', 'General Builder', null, 'steels in | Rate: 45.0', null, null, null, null, 0, 0, 0, 'Planned', 2035.0, 2035.0, 0, 'diary'),
  (v_user, v_project, 9, 'Labourers', 'Labour', 'General Builder', null, 'steels help plus disposal | Rate: 45.0', null, null, null, null, 0, 0, 0, 'Planned', 900.0, 900.0, 0, 'diary'),
  (v_user, v_project, 9, 'Toby', 'Labour', 'Skip/Disposal', null, 'Toby cleared out huge earth pile', null, null, null, null, 0, 0, 0, 'Planned', 1240.0, 1240.0, 0, 'diary'),
  (v_user, v_project, 10, 'Dave Builder', 'Labour', 'General Builder', null, 'Rate: 45.0', null, null, null, null, 0, 0, 0, 'Planned', 1640.0, 1640.0, 0, 'diary'),
  (v_user, v_project, 10, 'Owen Brickwork', 'Labour', 'General Builder', null, 'Rate: 45.0', null, null, null, null, 0, 0, 0, 'Planned', 675.0, 675.0, 0, 'diary'),
  (v_user, v_project, 10, 'Labourers', 'Labour', 'General Builder', null, 'Rate: 45.0', null, null, null, null, 0, 0, 0, 'Planned', 600.0, 600.0, 0, 'diary'),
  (v_user, v_project, 11, 'Dave Builder', 'Labour', 'General Builder', null, 'Rate: 45.0', null, null, null, null, 0, 0, 0, 'Planned', 400.0, 400.0, 0, 'diary'),
  (v_user, v_project, 11, 'Labourers', 'Labour', 'General Builder', null, 'Rate: 45.0', null, null, null, null, 0, 0, 0, 'Planned', 300.0, 300.0, 0, 'diary'),
  (v_user, v_project, 12, 'Scaffold', 'Materials', 'Scaffolder', null, 'Rate: 55.0', 'Scaffold', null, null, null, 0, 0, 0, 'Planned', 1000.0, 1000.0, 0, 'diary'),
  (v_user, v_project, 12, 'Nick Loft', 'Labour', 'General Builder', null, 'Rate: 45.0', null, null, null, null, 0, 0, 0, 'Planned', 3000.0, 3000.0, 0, 'diary'),
  (v_user, v_project, 13, 'Labourers', 'Labour', 'General Builder', null, 'Rate: 45.0', null, null, null, null, 0, 0, 0, 'Planned', 300.0, 300.0, 0, 'diary'),
  (v_user, v_project, 13, 'Adam - Clearance', 'Labour', 'Skip/Disposal', null, null, null, null, null, null, 0, 0, 0, 'Planned', 275.0, 275.0, 0, 'diary'),
  (v_user, v_project, 13, 'Nick Loft', 'Labour', 'General Builder', null, 'Rate: 45.0', null, null, null, null, 0, 0, 0, 'Planned', 2000.0, 2000.0, 0, 'diary'),
  (v_user, v_project, 14, 'Nick Loft', null, null, null, null, null, null, null, null, 0, 0, 0, 'Planned', 2520.0, 2520.0, 0, 'diary'),
  (v_user, v_project, 15, 'Nick Loft', 'Labour', 'General Builder', null, 'Rate: 45.0', null, null, null, null, 0, 0, 0, 'Planned', 2520.0, 2520.0, 0, 'diary'),
  (v_user, v_project, 15, 'Lawsons', 'Materials', 'Other', null, 'Rate: 50.0', 'Lawsons', null, null, null, 0, 0, 20, 'Planned', 5373.41, 4477.84, 0, 'diary'),
  (v_user, v_project, 16, 'Eurocell', 'Materials', 'General Builder', null, 'Rate: 45.0', 'Eurocell', null, null, null, 0, 0, 20, 'Planned', 201.29, 167.74, 0, 'diary'),
  (v_user, v_project, 16, 'Wunda UFH Materials', 'Materials', 'General Builder', null, 'Rate: 45.0', 'Wunda UFH Materials', null, null, null, 0, 0, 20, 'Planned', 600.59, 500.49, 0, 'diary'),
  (v_user, v_project, 16, 'Cabinets Direct (Kitchen)', 'Materials', 'General Builder', null, 'Rate: 45.0', 'Cabinets Direct (Kitchen)', null, null, null, 0, 0, 20, 'Planned', 5000.0, 4166.67, 0, 'diary'),
  (v_user, v_project, 16, 'Alspec Windows', 'Materials', 'Glazier', null, 'Rate: 55.0', 'Alspec Windows', null, null, null, 0, 0, 20, 'Planned', 8786.4, 7322.0, 0, 'diary'),
  (v_user, v_project, 16, 'Dave Builder', 'Labour', 'General Builder', null, 'Rate: 45.0', null, null, null, null, 0, 0, 20, 'Planned', 750.0, 625.0, 0, 'diary'),
  (v_user, v_project, 16, 'Owen Brickwork', 'Labour', 'General Builder', null, 'REPOINTING PLUS OTHER BITS | Rate: 45.0', null, null, null, null, 0, 0, 20, 'Planned', 560.0, 466.67, 0, 'diary'),
  (v_user, v_project, 16, 'Nick Loft', 'Labour', 'General Builder', null, 'Rate: 45.0', null, null, null, null, 0, 0, 20, 'Planned', 2520.0, 2100.0, 0, 'diary'),
  (v_user, v_project, 17, 'Miscl Roofing Materials', 'Materials', 'Roofer', null, 'Lead, Felt, Nails | Rate: 60.0', 'Miscl Roofing Materials', null, null, null, 0, 0, 20, 'Planned', 3145.42, 2621.18, 0, 'diary'),
  (v_user, v_project, 17, 'Sagar Roofing', 'Labour', 'Roofer', null, '£150-£180 per day to note | Rate: 60.0', null, null, null, null, 0, 0, 20, 'Planned', 2400.0, 2000.0, 0, 'diary'),
  (v_user, v_project, 17, 'Travis Perkins', 'Materials', 'General Builder', null, 'Brick repointing materials | Rate: 45.0', 'Travis Perkins', null, null, null, 0, 0, 20, 'Planned', 237.41, 197.84, 0, 'diary'),
  (v_user, v_project, 17, 'Eurocell', 'Materials', 'Roofer', null, 'Fascias / soffits / gutters | Rate: 60.0', 'Eurocell', null, null, null, 0, 0, 20, 'Planned', 284.86, 237.38, 0, 'diary'),
  (v_user, v_project, 17, 'Nick Loft', 'Labour', 'General Builder', null, 'Rate: 45.0', null, null, null, null, 0, 0, 20, 'Planned', 2520.0, 2100.0, 0, 'diary'),
  (v_user, v_project, 17, 'CAD Stairs', 'Materials', null, null, '50% DEPOSIT', 'CAD Stairs', null, null, null, 0, 0, 20, 'Planned', 1500.0, 1250.0, 0, 'diary'),
  (v_user, v_project, 17, 'St Albans Bathroom Centre', 'Materials', 'Bathroom Fitter', null, '50% DEPOSIT | Rate: 55.0', 'St Albans Bathroom Centre', null, null, null, 0, 0, 20, 'Planned', 4850.0, 4041.67, 0, 'diary'),
  (v_user, v_project, 17, 'Labourers', 'Labour', 'General Builder', null, '3 weeks of labour | Rate: 45.0', null, null, null, null, 0, 0, 20, 'Planned', 1350.0, 1125.0, 0, 'diary'),
  (v_user, v_project, 18, 'Saris', 'Materials', 'Glazier', null, 'Skylight inc upstand | Rate: 55.0', 'Saris', null, null, null, 0, 0, 20, 'Planned', 808.08, 673.4, 0, 'diary'),
  (v_user, v_project, 18, 'Sagar Roofing', 'Labour', 'Roofer', null, 'Rate: 60.0', null, null, null, null, 0, 0, 20, 'Planned', 600.0, 500.0, 0, 'diary'),
  (v_user, v_project, 18, 'Todds Doors', 'Materials', 'Carpenter/Joiner', null, 'Fire rated pocket door | Rate: 50.0', 'Todds Doors', null, null, null, 0, 0, 20, 'Planned', 742.5, 618.75, 0, 'diary'),
  (v_user, v_project, 18, 'Ryan Steels', 'Materials', null, null, 'Part payment Steels', 'Ryan Steels', null, null, null, 0, 0, 20, 'Planned', 1370.0, 1141.67, 0, 'diary'),
  (v_user, v_project, 18, 'Eaves Electrical', 'Materials', 'Electrician', null, 'part payment 1st fix | Rate: 65.0', 'Eaves Electrical', null, null, null, 0, 0, 20, 'Planned', 3105.0, 2587.5, 0, 'diary'),
  (v_user, v_project, 18, 'Lawsons', 'Materials', 'General Builder', null, 'Paid via AMEX | Rate: 45.0', 'Lawsons', null, null, null, 0, 0, 0, 'Planned', 4035.65, 4035.65, 0, 'diary'),
  (v_user, v_project, 18, 'Owen Brickwork', 'Labour', null, null, 'Chimney work plus other bits', null, null, null, null, 0, 0, 20, 'Planned', 425.0, 354.17, 0, 'diary'),
  (v_user, v_project, 18, 'Dave Builder', 'Labour', 'General Builder', null, 'Screed / GF WORKS CARPENTRY | Rate: 45.0', null, null, null, null, 0, 0, 20, 'Planned', 1600.0, 1333.33, 0, 'diary'),
  (v_user, v_project, 19, 'CAD Stairs', 'Materials', 'General Builder', null, 'Rate: 45.0', 'CAD Stairs', null, null, null, 0, 0, 20, 'Planned', 1500.0, 1250.0, 0, 'diary'),
  (v_user, v_project, 19, 'Johnstones Paint', 'Materials', 'Other', null, 'Exterior Paint | Rate: 50.0', 'Johnstones Paint', null, null, null, 0, 0, 20, 'Planned', 97.36, 81.13, 0, 'diary'),
  (v_user, v_project, 19, 'JJ Roofing', 'Materials', 'Roofer', null, 'Flat roof GF Materials | Rate: 60.0', 'JJ Roofing', null, null, null, 0, 0, 20, 'Planned', 1250.0, 1041.67, 0, 'diary'),
  (v_user, v_project, 19, 'Nick Loft', 'Labour', 'General Builder', null, 'Final payment nick | Rate: 45.0', null, null, null, null, 0, 0, 20, 'Planned', 1530.0, 1275.0, 0, 'diary'),
  (v_user, v_project, 19, 'Jewsons', 'Materials', 'General Builder', null, 'Drywall Adhesive | Rate: 45.0', 'Jewsons', null, null, null, 0, 0, 20, 'Planned', 471.6, 393.0, 0, 'diary'),
  (v_user, v_project, 19, 'Dave Builder', 'Labour', 'General Builder', null, 'Insulation in loft and other bits | Rate: 45.0', null, null, null, null, 0, 0, 20, 'Planned', 1500.0, 1250.0, 0, 'diary'),
  (v_user, v_project, 19, 'Sagar Roofing', 'Labour', 'Roofer', null, 'GF | Rate: 60.0', null, null, null, null, 0, 0, 20, 'Planned', 500.0, 416.67, 0, 'diary'),
  (v_user, v_project, 19, 'Labourers', 'Labour', 'General Builder', null, '2 weeks | Rate: 45.0', null, null, null, null, 0, 0, 20, 'Planned', 1440.0, 1200.0, 0, 'diary'),
  (v_user, v_project, 19, 'A1 Skips', 'Labour', 'Skip/Disposal', null, '2 skips', null, null, null, null, 0, 0, 20, 'Planned', 580.0, 483.33, 0, 'diary'),
  (v_user, v_project, 19, 'Adam - Clearance', 'Labour', 'Skip/Disposal', null, '2 loads van clearence', null, null, null, null, 0, 0, 20, 'Planned', 400.0, 333.33, 0, 'diary'),
  (v_user, v_project, 19, 'Owen Brickwork', 'Labour', 'General Builder', null, '2 DAYS FINISHING GROUND FLLOR | Rate: 45.0', null, null, null, null, 0, 0, 20, 'Planned', 750.0, 625.0, 0, 'diary'),
  (v_user, v_project, 20, 'Ryan Steels', 'Materials', 'General Builder', null, 'Final Steels | Rate: 45.0', 'Ryan Steels', null, null, null, 0, 0, 0, 'Planned', 1000.0, 1000.0, 0, 'diary'),
  (v_user, v_project, 20, 'Watts Roofing', 'Materials', null, null, 'Roofing materials', 'Watts Roofing', null, null, null, 0, 0, 0, 'Planned', 337.5, 337.5, 0, 'diary'),
  (v_user, v_project, 20, 'Pro Tiler', 'Materials', null, null, 'UFH EN SUITE', 'Pro Tiler', null, null, null, 0, 0, 0, 'Planned', 773.25, 773.25, 0, 'diary'),
  (v_user, v_project, 20, 'Dave Builder', 'Labour', null, null, null, null, null, null, null, 0, 0, 0, 'Planned', 2000.0, 2000.0, 0, 'diary'),
  (v_user, v_project, 20, 'Skips', 'Materials', null, null, null, 'Skips', null, null, null, 0, 0, 0, 'Planned', 290.0, 290.0, 0, 'diary'),
  (v_user, v_project, 20, 'Labourers', 'Labour', null, null, null, null, null, null, null, 0, 0, 0, 'Planned', 530.0, 530.0, 0, 'diary'),
  (v_user, v_project, 21, 'Roofers', 'Labour', null, null, '£400 materials of this amount', null, null, null, null, 0, 0, 0, 'Planned', 1800.0, 1800.0, 0, 'diary'),
  (v_user, v_project, 21, 'Cut Price Tiles', 'Materials', null, null, 'Deposit', 'Cut Price Tiles', null, null, null, 0, 0, 0, 'Planned', 200.0, 200.0, 0, 'diary'),
  (v_user, v_project, 21, 'Plastic Construction', 'Materials', null, null, 'Gutter materials', 'Plastic Construction', null, null, null, 0, 0, 0, 'Planned', 110.0, 110.0, 0, 'diary'),
  (v_user, v_project, 21, 'Pro Tiler', 'Materials', null, null, 'Tile Materials', 'Pro Tiler', null, null, null, 0, 0, 0, 'Planned', 423.79, 423.79, 0, 'diary'),
  (v_user, v_project, 21, 'Scaffold', 'Materials', null, null, 'Final payment', 'Scaffold', null, null, null, 0, 0, 0, 'Planned', 500.0, 500.0, 0, 'diary'),
  (v_user, v_project, 21, 'Dave Builder', 'Labour', null, null, null, null, null, null, null, 0, 0, 0, 'Planned', 1475.0, 1475.0, 0, 'diary'),
  (v_user, v_project, 21, 'Paint', 'Labour', null, null, 'Painting outside', null, null, null, null, 0, 0, 0, 'Planned', 170.0, 170.0, 0, 'diary'),
  (v_user, v_project, 21, 'Owen Brickwork', 'Labour', null, null, 'repointing', null, null, null, null, 0, 0, 0, 'Planned', 710.0, 710.0, 0, 'diary'),
  (v_user, v_project, 22, 'Todds Doors', 'Materials', null, null, 'Doors and hinges', 'Todds Doors', null, null, null, 0, 0, 0, 'Planned', 1595.4, 1595.4, 0, 'diary'),
  (v_user, v_project, 22, 'Cut Price Tiles', 'Materials', null, null, 'Tiles for bathrooms', 'Cut Price Tiles', null, null, null, 0, 0, 0, 'Planned', 1270.56, 1270.56, 0, 'diary'),
  (v_user, v_project, 22, 'Alspec Windows', 'Materials', null, null, 'Windows (£2k left)', 'Alspec Windows', null, null, null, 0, 0, 0, 'Planned', 4686.4, 4686.4, 0, 'diary'),
  (v_user, v_project, 22, 'Metres Direct LTD', 'Materials', null, null, 'Skirt + Architrave', 'Metres Direct LTD', null, null, null, 0, 0, 0, 'Planned', 1080.0, 1080.0, 0, 'diary'),
  (v_user, v_project, 22, 'Plasterers', 'Labour', null, null, '£5500 for house', null, null, null, null, 0, 0, 0, 'Planned', 2000.0, 2000.0, 0, 'diary'),
  (v_user, v_project, 22, 'Dryline - Boarding - Zoli', 'Labour', null, null, '£4000 for house', null, null, null, null, 0, 0, 0, 'Planned', 1500.0, 1500.0, 0, 'diary'),
  (v_user, v_project, 22, 'Corston', 'Materials', null, null, 'Handles, Locks', 'Corston', null, null, null, 0, 0, 0, 'Planned', 1049.88, 1049.88, 0, 'diary'),
  (v_user, v_project, 22, 'Dave Builder', 'Labour', null, null, '£135 materials', null, null, null, null, 0, 0, 0, 'Planned', 1135.0, 1135.0, 0, 'diary'),
  (v_user, v_project, 22, 'Lionvest', 'Materials', null, null, 'Wood Flooring - 80m2', 'Lionvest', null, null, null, 0, 0, 0, 'Planned', 3050.78, 3050.78, 0, 'diary'),
  (v_user, v_project, 22, 'Metres Direct LTD', 'Materials', null, null, 'Panelling / architrave/ picture rail', 'Metres Direct LTD', null, null, null, 0, 0, 0, 'Planned', 838.8, 838.8, 0, 'diary'),
  (v_user, v_project, 22, 'Topps Tiles', 'Materials', null, null, null, 'Topps Tiles', null, null, null, 0, 0, 0, 'Planned', 165.0, 165.0, 0, 'diary'),
  (v_user, v_project, 22, 'Adam - Clearance', 'Labour', null, null, null, null, null, null, null, 0, 0, 0, 'Planned', 200.0, 200.0, 0, 'diary'),
  (v_user, v_project, 23, 'ML Roofing', 'Labour', null, null, 'Lead work', null, null, null, null, 0, 0, 0, 'Planned', 150.0, 150.0, 0, 'diary'),
  (v_user, v_project, 23, 'AC Supplies', 'Materials', null, null, 'Jobs Screws etc from AC', 'AC Supplies', null, null, null, 0, 0, 0, 'Planned', 1035.0, 1035.0, 0, 'diary'),
  (v_user, v_project, 23, 'Topps Tiles', 'Materials', null, null, null, 'Topps Tiles', null, null, null, 0, 0, 0, 'Planned', 69.23, 69.23, 0, 'diary'),
  (v_user, v_project, 23, 'Lawsons', 'Materials', null, null, 'June Invoices', 'Lawsons', null, null, null, 0, 0, 0, 'Planned', 11222.63, 11222.63, 0, 'diary'),
  (v_user, v_project, 23, 'Pete Tiles', 'Labour', null, null, 'Bathroom tile plus wood floor', null, null, null, null, 0, 0, 0, 'Planned', 1420.0, 1420.0, 0, 'diary'),
  (v_user, v_project, 23, 'Plasterers', 'Labour', null, null, null, null, null, null, null, 0, 0, 0, 'Planned', 2000.0, 2000.0, 0, 'diary'),
  (v_user, v_project, 23, 'dryliner- zoli', 'Labour', null, null, null, null, null, null, null, 0, 0, 0, 'Planned', 1000.0, 1000.0, 0, 'diary'),
  (v_user, v_project, 23, 'Johnstones', 'Materials', null, null, 'Paint Ensuite plus 1st floor some of it', 'Johnstones', null, null, null, 0, 0, 0, 'Planned', 199.34, 199.34, 0, 'diary'),
  (v_user, v_project, 23, 'Maciekh', 'Labour', null, null, '2nd fix carpentry- 2nd floor', null, null, null, null, 0, 0, 0, 'Planned', 800.0, 800.0, 0, 'diary'),
  (v_user, v_project, 23, 'Mark Cornice', 'Materials', null, null, 'cornice supply and install', 'Mark Cornice', null, null, null, 0, 0, 0, 'Planned', 2924.25, 2924.25, 0, 'diary'),
  (v_user, v_project, 23, 'Dave Builder', 'Labour', null, null, '2nd fix - 1st floor', null, null, null, null, 0, 0, 0, 'Planned', 2110.0, 2110.0, 0, 'diary');

  insert into public.trade_lookups (user_id, name, default_rate, default_markup_pct) values
  (v_user, 'General Builder', 45.0, 10.0),
  (v_user, 'Carpenter/Joiner', 50.0, 10.0),
  (v_user, 'Plumber', 60.0, 10.0),
  (v_user, 'Electrician', 65.0, 10.0),
  (v_user, 'Plasterer', 55.0, 10.0),
  (v_user, 'Tiler', 55.0, 10.0),
  (v_user, 'Decorator', 45.0, 10.0),
  (v_user, 'Roofer', 60.0, 10.0),
  (v_user, 'Groundworker', 55.0, 10.0),
  (v_user, 'Kitchen Fitter', 55.0, 10.0),
  (v_user, 'Bathroom Fitter', 55.0, 10.0),
  (v_user, 'Glazier', 55.0, 10.0),
  (v_user, 'Scaffolder', 55.0, 10.0),
  (v_user, 'Flooring Installer', 50.0, 10.0),
  (v_user, 'Skip/Disposal', 0.0, 0.0),
  (v_user, 'Other', 50.0, 10.0)
  on conflict (user_id, name) do update
    set default_rate = excluded.default_rate,
        default_markup_pct = excluded.default_markup_pct;

  insert into public.project_weeks (user_id, project_id, week_number, completion_pct)
  select v_user, v_project, generate_series(1, 23), 0
  on conflict (project_id, week_number) do nothing;

  raise notice 'Imported project % (111 diary rows, no ledger).', v_project;
end $$;

-- ------------------------------------------------------------------
-- Self-check: every week's diary total must equal the spreadsheet's
-- 'Summary' -> 'By Week (Totals)' figure. Any disagreement aborts the
-- transaction, so a bad import can never be committed by accident.
-- ------------------------------------------------------------------
do $$
declare
  v_user  uuid := '5d3fc9ff-92a3-4923-a18b-7eb5eade3105';
  r       record;
  v_bad   int := 0;
begin
  for r in
    with expected(week_number, sheet_total) as (values
      (1, 1770.0::numeric),
      (2, 1675.0::numeric),
      (3, 525.0::numeric),
      (4, 1550.0::numeric),
      (5, 3205.0::numeric),
      (6, 2500.0::numeric),
      (7, 2048.4::numeric),
      (8, 2425.0::numeric),
      (9, 6110.0::numeric),
      (10, 2915.0::numeric),
      (11, 700.0::numeric),
      (12, 4000.0::numeric),
      (13, 2575.0::numeric),
      (14, 2520.0::numeric),
      (15, 7893.41::numeric),
      (16, 18418.28::numeric),
      (17, 16287.68::numeric),
      (18, 12686.23::numeric),
      (19, 10018.96::numeric),
      (20, 4930.75::numeric),
      (21, 5388.79::numeric),
      (22, 18571.82::numeric),
      (23, 22930.45::numeric)
    ),
    got as (
      select e.week_number,
             sum(e.actual_amount * (1 + e.vat_rate / 100)) as app_total
      from public.expense_entries e
      join public.projects p on p.id = e.project_id
      where p.user_id = v_user
        and p.name   = '46 Glenferrie Road'
        and e.source = 'diary'
        and e.status <> 'Cancelled'
      group by e.week_number
    )
    select expected.week_number, expected.sheet_total,
           coalesce(got.app_total, 0) as app_total
    from expected left join got using (week_number)
    order by expected.week_number
  loop
    if abs(r.app_total - r.sheet_total) > 0.01 then
      v_bad := v_bad + 1;
      raise warning 'Week %: app % <> spreadsheet %',
        r.week_number, round(r.app_total, 2), r.sheet_total;
    end if;
  end loop;

  if v_bad > 0 then
    raise exception '% week(s) do not match the spreadsheet — nothing committed.', v_bad;
  end if;
  raise notice 'All 23 weeks match the spreadsheet.';
end $$;

commit;
-- rollback;  -- use instead of commit if the numbers look wrong

-- ==================================================================
-- NEXT STEP: run 0008_transaction_core.sql again, immediately.
-- It is re-runnable. Its backfill was wiped by the project delete
-- above (purchases.project_id is on delete cascade), and its suppliers
-- and items were cleared on purpose so the old File 2 merchants do not
-- linger. Until you re-run it, /suppliers and /items will be empty.
-- ==================================================================

-- ------------------------------------------------------------------
-- Report. Compare these against the spreadsheet's Summary tab.
-- 'Ledger rows' must now be 0.
-- ------------------------------------------------------------------
select 'Total Quoted'      as card, sum(quoted_amount)                          as value
from public.expense_entries e join public.projects p on p.id = e.project_id
where p.user_id = '5d3fc9ff-92a3-4923-a18b-7eb5eade3105' and p.name = '46 Glenferrie Road'
  and e.source = 'diary' and e.status <> 'Cancelled'
union all
select 'Actual Total (incl. VAT)', sum(actual_amount * (1 + vat_rate / 100))
from public.expense_entries e join public.projects p on p.id = e.project_id
where p.user_id = '5d3fc9ff-92a3-4923-a18b-7eb5eade3105' and p.name = '46 Glenferrie Road'
  and e.source = 'diary' and e.status <> 'Cancelled'
union all
select 'Paid to Date', sum(paid_amount)
from public.expense_entries e join public.projects p on p.id = e.project_id
where p.user_id = '5d3fc9ff-92a3-4923-a18b-7eb5eade3105' and p.name = '46 Glenferrie Road'
  and e.source = 'diary' and e.status <> 'Cancelled'
union all
select 'Weeks Tracked', count(distinct week_number)
from public.expense_entries e join public.projects p on p.id = e.project_id
where p.user_id = '5d3fc9ff-92a3-4923-a18b-7eb5eade3105' and p.name = '46 Glenferrie Road'
  and e.source = 'diary' and e.status <> 'Cancelled'
union all
select 'Diary rows', count(*)
from public.expense_entries e join public.projects p on p.id = e.project_id
where p.user_id = '5d3fc9ff-92a3-4923-a18b-7eb5eade3105' and p.name = '46 Glenferrie Road' and e.source = 'diary'
union all
select 'Ledger rows', count(*)
from public.expense_entries e join public.projects p on p.id = e.project_id
where p.user_id = '5d3fc9ff-92a3-4923-a18b-7eb5eade3105' and p.name = '46 Glenferrie Road' and e.source = 'ledger';
